"""Tool-Artifact Owner integration tests (WP09 / FR-007, FR-008, FR-012, NFR-002).

Covers the generalisation of the coordination ``BookkeepingTransaction`` into the
owner of bytes spec-kitty generates on ANY surface:

* **Non-coord destination** (T046) — the single owner compensator captures and
  restores generated bytes on a primary-checkout (non-coord) surface, byte-identical.
* **Subprocess-byproduct enrolment** (T047 / C3) — bytes a spawned child process
  CREATES are committed on success and reverted on abort, never detected-warned-and-
  abandoned. Exercised both through the ``atomic_write`` module functions and through
  ``BookkeepingTransaction.enroll_subprocess_byproducts``.
* **Executor adoption / one compensator** (T048 / TAO-3) — the merge executor's
  capture/restore now routes through the SAME owner compensator.
* **Canonical churn classifier** (T049 / FR-012) — one classifier every gate consults.
* **NFR-002** — a deterministic fork()+SIGKILL barrier at the atomic commit seam,
  POSIX-gated, asserting the enrolled path remains byte-identical to its
  pre-transaction bytes before replace and reaches its committed post-state, plus a
  recovery-verified commit-spanning arm (re-invoke reaches the committed state, no
  residue) for the platforms where kill-atomicity cannot be asserted (Windows gap:
  recovery-only).

The fork+SIGKILL harness follows the ``tests/integration/test_intake_atomic_writes.py``
idiom.
"""

from __future__ import annotations

import contextlib
import os
import select
import signal
import subprocess
from pathlib import Path

import pytest

from specify_cli.coordination import atomic_write as aw
from specify_cli.coordination.atomic_write import (
    capture_generated_artifact_snapshots,
    enroll_subprocess_byproducts,
    restore_generated_artifact_snapshots,
    subprocess_created_paths,
)
from specify_cli.coordination.coherence import is_toolchain_generated_churn
from specify_cli.coordination.transaction import BookkeepingTransaction
from specify_cli.status.emit import build_status_event

pytestmark = [pytest.mark.integration, pytest.mark.git_repo]


MISSION_SLUG = "owner-demo-feature"
MID8 = "01J8XW9K"
MISSION_ID = "01J8XW9K00000000000000000P"  # 26-char placeholder ULID
COORD_BRANCH = f"kitty/mission-{MISSION_SLUG}-{MID8}"
FEATURE_DIRNAME = f"{MISSION_SLUG}-{MID8}"


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True
    )


@pytest.fixture
def coord_repo(tmp_path: Path) -> Path:
    """Tmp repo with the coordination branch pre-created (post-WP03 state)."""
    r = tmp_path / "repo"
    r.mkdir()
    _git(r, "init", "-q", "-b", "main")
    _git(r, "config", "user.email", "t@example.com")
    _git(r, "config", "user.name", "Test")
    _git(r, "config", "commit.gpgsign", "false")
    (r / "seed.txt").write_text("seed\n")
    _git(r, "add", "seed.txt")
    _git(r, "commit", "-q", "-m", "initial")
    _git(r, "branch", COORD_BRANCH)
    feature_dir = r / "kitty-specs" / FEATURE_DIRNAME
    feature_dir.mkdir(parents=True)
    (feature_dir / "meta.json").write_text(
        "{\n"
        f'  "mission_id": "{MISSION_ID}",\n'
        f'  "mission_slug": "{FEATURE_DIRNAME}",\n'
        '  "target_branch": "main",\n'
        f'  "coordination_branch": "{COORD_BRANCH}"\n'
        "}\n",
        encoding="utf-8",
    )
    return r


def _acquire(repo: Path, operation: str) -> BookkeepingTransaction:
    return BookkeepingTransaction.acquire(
        repo_root=repo,
        mission_id=MISSION_ID,
        mission_slug=MISSION_SLUG,
        mid8=MID8,
        destination_ref=COORD_BRANCH,
        operation=operation,
    )


# ---------------------------------------------------------------------------
# T046 — non-coord destination (owner compensator on a primary-checkout surface)
# ---------------------------------------------------------------------------


def test_non_coord_destination_round_trip(tmp_path: Path) -> None:
    """The owner captures + restores generated bytes on a NON-coord surface.

    Primary-surface generated writes (e.g. the VCS lock) now have an owner: the
    single compensator, against any declared trusted roots.
    """
    primary = tmp_path / "primary"
    (primary / "kitty-specs" / "m").mkdir(parents=True)
    artifact = primary / "kitty-specs" / "m" / "status.events.jsonl"
    artifact.write_bytes(b"ORIGINAL\n")

    snapshots = capture_generated_artifact_snapshots(
        artifact, trusted_roots=[primary / "kitty-specs"]
    )
    artifact.write_bytes(b"MUTATED-BY-TOOL\n")
    restore_generated_artifact_snapshots(snapshots)

    assert artifact.read_bytes() == b"ORIGINAL\n"


def test_non_coord_destination_created_file_is_unlinked_on_restore(tmp_path: Path) -> None:
    """A path absent pre-transaction snapshots as None → restore unlinks it."""
    primary = tmp_path / "primary"
    (primary / ".kittify" / "runtime" / "merge").mkdir(parents=True)
    lock = primary / ".kittify" / "runtime" / "merge" / "vcs.lock"

    snapshots = capture_generated_artifact_snapshots(
        lock, trusted_roots=[primary / ".kittify" / "runtime" / "merge"]
    )
    lock.write_bytes(b"acquired\n")
    restore_generated_artifact_snapshots(snapshots)

    assert not lock.exists()


def test_non_coord_destination_rejects_untrusted_surface(tmp_path: Path) -> None:
    """Containment is owned by the compensator, not the caller's surface package."""
    primary = tmp_path / "primary"
    (primary / "kitty-specs").mkdir(parents=True)
    outside = tmp_path / "elsewhere" / "evil.json"

    with pytest.raises(ValueError):
        capture_generated_artifact_snapshots(
            outside, trusted_roots=[primary / "kitty-specs"]
        )


# ---------------------------------------------------------------------------
# T047 / C3 — subprocess-byproduct enrolment (module-level owner functions)
# ---------------------------------------------------------------------------


def test_subprocess_byproducts_reverted_on_abort(tmp_path: Path) -> None:
    """A child process CREATES files; on abort they are reverted, not abandoned."""
    workdir = tmp_path / "work"
    workdir.mkdir()
    before = set(workdir.iterdir())

    # A real spec-kitty-spawned child (stand-in for a gate's pytest run) that
    # creates byproduct files.
    subprocess.run(
        [
            "python",
            "-c",
            (
                "import pathlib,sys;"
                "d=pathlib.Path(sys.argv[1]);"
                "(d/'.pytest_cache').mkdir();"
                "(d/'.pytest_cache'/'v.json').write_text('cache');"
                "(d/'coverage.xml').write_text('<coverage/>')"
            ),
            str(workdir),
        ],
        check=True,
    )
    after = {p for p in workdir.rglob("*") if p.is_file()}
    created = subprocess_created_paths(before, after)
    assert created, "the child must have created byproduct files"

    snapshots = enroll_subprocess_byproducts(created, trusted_roots=[workdir])
    # Abort: revert the byproducts through the single compensator.
    restore_generated_artifact_snapshots(snapshots)

    assert not (workdir / "coverage.xml").exists()
    assert not (workdir / ".pytest_cache" / "v.json").exists()


def test_subprocess_byproducts_committed_on_success(tmp_path: Path) -> None:
    """On success (no rollback) the enrolled byproducts survive — committed."""
    workdir = tmp_path / "work"
    workdir.mkdir()
    byproduct = workdir / "coverage.xml"
    byproduct.write_text("<coverage/>")

    # Enrolment does not itself delete anything; only a rollback restores.
    snapshots = enroll_subprocess_byproducts([byproduct], trusted_roots=[workdir])
    assert snapshots == {byproduct.resolve(strict=False): None}
    assert byproduct.exists()


# ---------------------------------------------------------------------------
# T047 / C3 — subprocess-byproduct enrolment through the owner transaction
# ---------------------------------------------------------------------------


def test_transaction_enrolled_byproduct_reverted_on_rollback(coord_repo: Path) -> None:
    """A byproduct enrolled in a transaction is unlinked when the step aborts."""
    txn = _acquire(coord_repo, "byproduct_rollback")
    byproduct = txn.worktree_root / "kitty-specs" / FEATURE_DIRNAME / "child-output.txt"
    byproduct.parent.mkdir(parents=True, exist_ok=True)
    # Enrol BEFORE the child creates it (pre-state absent).
    txn.enroll_subprocess_byproducts(byproduct)
    try:
        with txn:
            # Stand-in for the spawned child writing a byproduct.
            byproduct.write_bytes(b"created-by-child\n")
            assert byproduct.exists()
            raise RuntimeError("injected step failure")
    except RuntimeError:
        pass

    # C3/TAO-2: the created byproduct is reverted, not abandoned as an orphan.
    assert not byproduct.exists()


def test_transaction_enrolled_byproduct_survives_commit(coord_repo: Path) -> None:
    """On a clean exit the enrolled byproduct is committed (survives)."""
    txn = _acquire(coord_repo, "byproduct_commit")
    byproduct = txn.worktree_root / "kitty-specs" / FEATURE_DIRNAME / "child-output.txt"
    byproduct.parent.mkdir(parents=True, exist_ok=True)
    txn.enroll_subprocess_byproducts(byproduct)
    with txn:
        byproduct.write_bytes(b"created-by-child\n")
        txn.commit("chore: byproduct commit")

    assert byproduct.exists()
    assert byproduct.read_bytes() == b"created-by-child\n"


# ---------------------------------------------------------------------------
# T048 / TAO-3 — executor adoption uses the single owner compensator
# ---------------------------------------------------------------------------


def test_executor_capture_restore_uses_owner_compensator(tmp_path: Path) -> None:
    """The merge executor's snapshot/restore routes through the owner compensator."""
    from specify_cli.consolidation.executor import _capture_merge_snapshots

    main_repo = tmp_path / "repo"
    events = main_repo / "kitty-specs" / "m" / "status.events.jsonl"
    events.parent.mkdir(parents=True)
    events.write_bytes(b"approved\n")
    state = main_repo / ".kittify" / "merge-state.json"
    state.parent.mkdir(parents=True)
    state.write_bytes(b'{"completed_wps": []}\n')

    snapshots = _capture_merge_snapshots(main_repo, events, state)
    events.write_bytes(b"approved\ndone\n")
    state.write_bytes(b'{"completed_wps": ["WP01"]}\n')

    restore_generated_artifact_snapshots(snapshots)

    assert events.read_bytes() == b"approved\n"
    assert state.read_bytes() == b'{"completed_wps": []}\n'


# ---------------------------------------------------------------------------
# T049 / FR-012 — one canonical churn classifier
# ---------------------------------------------------------------------------


def test_canonical_churn_classifier_unifies_bookkeeping_and_residue() -> None:
    """The single classifier recognises spec-kitty bookkeeping AND coord residue,
    and does NOT flag operator planning artifacts (GA-1: by kind/origin)."""
    # self-bookkeeping (meta.json is spec-kitty's own metadata)
    assert is_toolchain_generated_churn("kitty-specs/m/meta.json")
    # coord-partition residue (the append-only status log)
    assert is_toolchain_generated_churn(
        "kitty-specs/m/status.events.jsonl", mission_slug="m"
    )
    # operator-authored planning artifact is NOT toolchain churn
    assert not is_toolchain_generated_churn("kitty-specs/m/spec.md", mission_slug="m")


# ---------------------------------------------------------------------------
# NFR-002 — deterministic fork()+SIGKILL commit-seam barrier (POSIX-gated)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not hasattr(os, "fork"),
    reason="NFR-002 kill-atomicity requires POSIX os.fork(); Windows is recovery-only",
)
def test_nfr002_enrolled_path_never_observes_a_third_state(
    tmp_path: Path,
) -> None:
    """A kill at the reached replace seam preserves pre; a full write reaches post."""
    worktree = tmp_path / "wt"
    worktree.mkdir()
    target = worktree / "artifact.bin"
    pre = b"PRE-" * 8
    post = bytes((i * 31 + 7) % 256 for i in range(1024)) * 1024
    assert post != pre
    resolve = aw._resolve_confined_artifact_path

    aw._write_confined_artifact_bytes(worktree, target, pre, resolve=resolve)
    ready_read, ready_write = os.pipe()
    pid = os.fork()
    if pid == 0:  # pragma: no cover — child process
        os.close(ready_read)

        def _block_at_replace(*args: object, **kwargs: object) -> None:
            del args, kwargs
            os.write(ready_write, b"1")
            signal.pause()

        aw.os.replace = _block_at_replace  # type: ignore[assignment]
        try:
            aw._write_confined_artifact_bytes(worktree, target, post, resolve=resolve)
        except BaseException:
            os._exit(2)
        os._exit(0)

    os.close(ready_write)
    readable, _, _ = select.select([ready_read], [], [], 5.0)
    reached_replace = os.read(ready_read, 1) if readable else b""
    os.close(ready_read)
    with contextlib.suppress(ProcessLookupError):
        os.kill(pid, signal.SIGKILL)
    _, status = os.waitpid(pid, 0)

    assert reached_replace == b"1", "child never reached the atomic replace seam"
    assert os.WIFSIGNALED(status) and os.WTERMSIG(status) == signal.SIGKILL
    assert target.read_bytes() == pre
    assert list(worktree.glob(".spec-kitty-*.tmp")), (
        "kill at the reached replace seam must leave proof of the completed temp write"
    )

    aw._write_confined_artifact_bytes(worktree, target, post, resolve=resolve)
    assert target.read_bytes() == post


def test_nfr002_commit_spanning_recovery_reaches_committed_state(coord_repo: Path) -> None:
    """Commit-spanning arm (recovery, not kill-atomicity; the Windows-safe path).

    A committed transition is durable; re-invoking the same enrol+commit is an
    idempotent no-op that reaches the committed state with NO residue — the recovery
    property NFR-002 requires for commit-spanning paths.
    """
    event = build_status_event(
        mission_slug=MISSION_SLUG,
        mission_id=MISSION_ID,
        wp_id="WP01",
        from_lane="planned",
        to_lane="claimed",
        actor="implementer-ivan",
    )
    with _acquire(coord_repo, "commit_span") as txn:
        txn.append_event(event)
        first = txn.commit("status: WP01 → claimed")
    assert first.commit_sha

    # Recovery: a resume re-stages the SAME (already-committed, unchanged) status
    # paths and commits idempotently. The tree is byte-identical to HEAD, so the
    # follow-up reaches the committed state as a no-op — no partial residue.
    with _acquire(coord_repo, "commit_span_recovery") as txn2:
        txn2.stage_path(txn2.feature_dir / "status.events.jsonl")
        txn2.stage_path(txn2.feature_dir / "status.json")
        receipt = txn2.commit_idempotent("status: WP01 → claimed")
    assert receipt.is_noop
    assert receipt.commit_sha == first.commit_sha
