"""Installed copies of removed skills, for the charter-pack cutover (FR-012 step 7, FR-008, #3732).

Contract: ``kitty-specs/charter-pack-cutover-01M491G6/contracts/upgrade-migration.md`` step 7.

For each project skill root of each configured agent
(``AGENT_SKILL_CONFIG[agent]["skill_roots"]``, deduplicated; a root that does
not exist is skipped, never created), every ``<root>/<removed name>/`` is
removed through :func:`specify_cli.asset_preservation.guard_destructive_removal`
when its ownership is proven, either

* by the managed-skills manifest (:class:`~specify_cli.asset_preservation.ManifestProver`:
  every file has an entry whose hash matches), or
* by :class:`_FrozenTreeHashProver`: the tree holds exactly the files a shipped
  source held and each one hashes to :data:`SHIPPED_SKILL_HASHES`.

Anything else (an edited copy, an extra file, a symlink) stays in place and is
reported once (``skills_kept``, ``preserved_paths``). A removed copy's entries are
dropped from ``.kittify/skills-manifest.json`` so no orphan entry remains, and so
are a kept copy's (owner ruling A, US4): the kept copy becomes user-owned, so the
upgrade finalizer never offers to overwrite it and later upgrades exit 0. A
name the installed CLI still ships is left alone (the upgrade finalizer would
reinstall it); every name is live once its source is deleted (FR-008).

:data:`SHIPPED_SKILL_HASHES` are the sha256 of every installable file
(``SKILL.md``, ``references/``, ``scripts/``, ``assets/``) under
``src/charter/offering/skills/<name>/`` as of the cutover, generated by a
scratch script from those sources; installed copies are byte copies of them.
Limitation: copies installed by an older release whose bytes differ are not
covered, so an unmanifested older copy is kept and reported (the safe
direction). ``spec-kitty-constitution-doctrine`` ships no source here: only a
manifested copy of it is removed.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType

from specify_cli.asset_preservation import AnyProver, ManifestProver, guard_destructive_removal
from specify_cli.tool_surface.operations import OwnershipProof

from ._charter_pack_cutover_report import CutoverReport
from .base import MigrationStateUnreadableError

__all__ = ["remove_skill_copies"]

#: Skill names FR-008 removes (plus ``spec-kitty-constitution-doctrine``, ruling FI-S4).
REMOVED_SKILL_NAMES: tuple[str, ...] = (
    "spk-doctrine-charter",
    "spk-doctrine-glossary",
    "spk-doctrine-profile-load",
    "spk-doctrine-spdd-reasons",
    "spk-doctrine-bulk-edit",
    "spk-doctrine-semantic-compression",
    "spk-doctrine-show-me",
    "spec-kitty-charter-doctrine",
    "spec-kitty-glossary-context",
    "spec-kitty-bulk-edit-classification",
    "spec-kitty-spdd-reasons",
    "ad-hoc-profile-load",
    "spec-kitty-constitution-doctrine",
)

#: Skill name -> {path relative to the skill directory -> sha256} of the shipped source.
SHIPPED_SKILL_HASHES: Mapping[str, Mapping[str, str]] = MappingProxyType(
    {
        "ad-hoc-profile-load": MappingProxyType(
            {
                "SKILL.md": "b2de95a2b9c07d1a954fb9311c2ad58f219579c7b74a2fd225eb6aa8a098064e",
            }
        ),
        "spec-kitty-bulk-edit-classification": MappingProxyType(
            {
                "SKILL.md": "a28a15446fa4423b8ac4127f7987c578d774298bc9d24475bba04f403a7c9559",
            }
        ),
        "spec-kitty-charter-doctrine": MappingProxyType(
            {
                "SKILL.md": "6d87424832376a26fdd47cc33e1764061340f725675c3751ec5f5757ea12447f",
                "references/charter-command-map.md": "2bc9dfd0401a3b578548ae2226196277e8591e6281f5a6de480b3958bb0957ce",
                "references/doctrine-artifact-structure.md": "1cec564371e30ba896eb6d071c9c77636eb29ae1ffc609d915ad4e58e06b27c0",
            }
        ),
        "spec-kitty-glossary-context": MappingProxyType(
            {
                "SKILL.md": "ae7ebc18de82f72cec93bc9ba0ed5ce194ba7a8648223c1a680a9e2946086b55",
                "references/glossary-field-guide.md": "9cddfccd64773976cf97450fa983dc8cc3aa7354a6002d763a7fa3ac65ff9ace",
                "references/semantic-drift-examples.md": "d2df36b399316d12d05b10b36dab19a3eb330ed9c502b9b0fa2bb35ecf8341c4",
            }
        ),
        "spec-kitty-spdd-reasons": MappingProxyType(
            {
                "SKILL.md": "eaebcad4f682073a52ea49e89fb10b2f15e641bdfae18778e323618395e2b726",
            }
        ),
        "spk-doctrine-bulk-edit": MappingProxyType(
            {
                "SKILL.md": "6ff391973da8c312833a25b2f47cc9a7ac16ab7ae3e90f61e0eb4e20eb24b243",
            }
        ),
        "spk-doctrine-charter": MappingProxyType(
            {
                "SKILL.md": "4aa5bacce79f17941a5b6f659c743bb47a1836a483d4c5fb8b0930555946de62",
            }
        ),
        "spk-doctrine-glossary": MappingProxyType(
            {
                "SKILL.md": "a5034728033c4defb6de4601dd05d612143ca6e7ea932b531decdfea34d4adbc",
            }
        ),
        "spk-doctrine-profile-load": MappingProxyType(
            {
                "SKILL.md": "2bee21c977e783fd6bac653c4ff498a89b0b310c55fad2bd443882871a599f78",
                "references/profile-load-mechanics.md": "bd7f57248ff69db931f95408e223129c1ba657ffc09caebbee70731986707e1c",
            }
        ),
        "spk-doctrine-semantic-compression": MappingProxyType(
            {
                "SKILL.md": "396e0c56e4adf6ef27008a5bcf758dc8efdca9a5b13acaf351ba3992ca9adcfb",
            }
        ),
        "spk-doctrine-show-me": MappingProxyType(
            {
                "SKILL.md": "2543980c699fa3291c6adef1d5b04da0170d082770206e31a7b34c259bb57782",
                "assets/MERMAID_DIAGRAMMING.md": "ec87bcad76c3d2d1beaabcdbc0bfe631ac6ad5f6999d5204852a4b9471740bf4",
                "assets/PLANTUML_DIAGRAMMING.md": "2abe26ed70df8a2d71d02eb80e7037a1282005be3693c5e2df4db411056cec34",
                "assets/mermaid-theme-bluegray-conversation-template.md": "d0dfd495ed1aaa11ad638e6c07c5487163d0f52bf4de64a969514ecf1134f5ef",
                "assets/mermaid-theme-common-template.md": "15aee12ab3d7302c88db47a31f2c3d0d865cb016be10138d3eeb0fa62ebaf645",
                "references/humanlayer-origin-and-license.md": "fc0909ee648e1af31555305c40d66ca12367e87100d1481c59604bd6445a4a32",
                "references/spec-kitty-diagram-sources.md": "d9f6216f0270fb768ae1b94580d087bdf96158a7c1775c743d0764a16527e2fe",
            }
        ),
        "spk-doctrine-spdd-reasons": MappingProxyType(
            {
                "SKILL.md": "9edcd544867d95d3de98cc884e1e2d3d9e61b4d24cf8468f5cb586772794eb94",
            }
        ),
    }
)


class _FrozenTreeHashProver:
    """Proves a skill directory removable when it is a byte copy of the shipped source."""

    def __init__(self, hashes: Mapping[str, str]) -> None:
        self._hashes = hashes

    def prove(self, path: Path, project_path: Path) -> OwnershipProof | None:
        if not self._hashes or path.is_symlink() or not path.is_dir():
            return None
        from specify_cli.skills.manifest import compute_content_hash

        found: dict[str, str] = {}
        for member in sorted(path.rglob("*")):
            if member.is_symlink():
                return None
            if member.is_file():
                try:
                    found[member.relative_to(path).as_posix()] = compute_content_hash(member)
                except OSError:
                    return None
        if found != {rel: f"sha256:{digest}" for rel, digest in self._hashes.items()}:
            return None
        return OwnershipProof("canonical_content", f"shipped-skill-hash:{path.relative_to(project_path).as_posix()}")


@dataclass(frozen=True)
class SkillCopy:
    """One installed directory named after a removed skill."""

    path: Path
    name: str

    def rel(self, project: Path) -> str:
        return self.path.relative_to(project).as_posix()


def _configured_skill_roots(project: Path) -> list[str]:
    from specify_cli.core.agent_config import AgentConfigError, load_agent_config
    from specify_cli.core.config import AGENT_SKILL_CONFIG

    try:
        agents = load_agent_config(project).available
    except AgentConfigError as exc:
        raise MigrationStateUnreadableError(f"{exc}; fix the file, then run `spec-kitty upgrade` again") from exc
    roots: list[str] = []
    for agent in agents:
        configured = AGENT_SKILL_CONFIG.get(agent, {}).get("skill_roots")
        for root in configured if isinstance(configured, list) else []:
            normalised = root.rstrip("/")
            if normalised not in roots:
                roots.append(normalised)
    return roots


def _shipped_skill_names() -> frozenset[str]:
    """Names the installed CLI's skill catalog still ships (the upgrade finalizer installs those).

    Raises:
        MigrationStateUnreadableError: no shipped skill catalog is found, so a
            removed name the CLI still ships cannot be told apart; fail closed
            rather than remove a skill the finalizer would reinstall.
    """
    from specify_cli.skills.catalog import resolve_builtin_skill_catalog

    registry = resolve_builtin_skill_catalog()
    if registry is None:
        raise MigrationStateUnreadableError(
            "the installed CLI ships no skill catalog, so the removed skills it still ships cannot be told apart; "
            "reinstall spec-kitty, then run `spec-kitty upgrade` again"
        )
    return frozenset(skill.name for skill in registry.discover_skills())


def find_removed_skill_copies(project_path: Path) -> list[SkillCopy]:
    """Every ``<configured skill root>/<removed name>`` present in *project_path* (nothing is written).

    A name the installed catalog still ships is skipped: the upgrade finalizer
    would install it again right after, so removing it would only churn.
    """
    shipped = _shipped_skill_names()
    names = [name for name in REMOVED_SKILL_NAMES if name not in shipped]
    copies: list[SkillCopy] = []
    for root in _configured_skill_roots(project_path) if names else []:
        base = project_path / root
        if not base.is_dir():
            continue
        copies.extend(SkillCopy(base / name, name) for name in names if os.path.lexists(base / name))
    return copies


def _prover(name: str) -> AnyProver:
    return AnyProver([ManifestProver(), _FrozenTreeHashProver(SHIPPED_SKILL_HASHES.get(name, {}))])


def _drop_manifest_entries(project: Path, removed: list[str]) -> None:
    """Drop the manifest entries of every removed directory (project-relative paths)."""
    from specify_cli.skills.manifest import load_manifest, save_manifest

    manifest = load_manifest(project, strict=True)
    if manifest is None:
        return
    prefixes = tuple(f"{rel}/" for rel in removed)
    kept = [entry for entry in manifest.entries if not entry.installed_path.startswith(prefixes)]
    if len(kept) != len(manifest.entries):
        manifest.entries = kept
        save_manifest(manifest, project)


def _remove_one(project: Path, copy: SkillCopy, report: CutoverReport, *, dry_run: bool) -> bool:
    """Remove or keep *copy*; ``True`` once it is settled (removed or kept), ``False`` on an error."""
    rel = copy.rel(project)
    try:
        verdict = guard_destructive_removal(copy.path, project, prover=_prover(copy.name), is_tree=True, dry_run=dry_run)
    except OSError as exc:
        report.errors.append(f"{rel} could not be removed ({exc}); close any program holding it, then run `spec-kitty upgrade` again")
        return False
    if verdict.owned:
        report.skills_removed.append(f"{rel} ({copy.name}; {verdict.reason})")
        return True
    report.skills_kept.append(
        f"{rel} ({copy.name}; edited or not a shipped copy, left in place and no longer managed by spec-kitty; remove it by hand once you no longer need it)"
    )
    report.preserved_paths.append(rel)
    return True


def remove_skill_copies(project_path: Path, *, dry_run: bool) -> CutoverReport:
    """Remove every proven copy of a removed skill (unless *dry_run*); keep and report the rest.

    Every settled copy, removed or kept, leaves the skills manifest: a removed
    one so no orphan entry remains, a kept one so it becomes user-owned. A copy
    whose removal failed keeps its entries, so the next upgrade can still prove it.
    """
    report = CutoverReport()
    settled = [copy.rel(project_path) for copy in find_removed_skill_copies(project_path) if _remove_one(project_path, copy, report, dry_run=dry_run)]
    if settled and not dry_run:
        try:
            _drop_manifest_entries(project_path, settled)
        except (OSError, ValueError) as exc:
            report.errors.append(f".kittify/skills-manifest.json could not be updated ({exc}); run `spec-kitty upgrade` again")
    return report
