"""Migration 3.1.2: Safely remove project-level spec-kitty command files.

As of 3.1.2, slash commands (``spec-kitty.*.md``, ``spec-kitty.*.toml``, etc.)
are installed globally to the user's home agent directories
(``~/.claude/commands/``, ``~/.gemini/commands/``, etc.) by
``ensure_global_agent_commands()`` at CLI startup. Per-project copies are no
longer needed, but removing them must preserve any user customization the CLI
cannot prove safe to delete.

This migration removes project-local command files only when:
  1. The global runtime (``~/.kittify/missions/``) is present.
  2. The exact global replacement file exists for the same agent/filename.
  3. The local file is proven spec-kitty-generated by the version marker scan.

A file that lacks the version marker is user-authored or unproven: it is
preserved in place and reported for manual review (the only "held" case). A
file that carries the marker but cannot be removed yet (global runtime or exact
global replacement absent, or the unlink failed) is ours, not customised: it is
kept in place with a note and is NOT held for review. Migrations are
version-windowed (``MigrationRegistry.get_applicable``), so this migration does
not run again once the project is past it: a generated command kept here stays
project-local, and once the operator later gets the global copy both exist (a
local plus a global duplicate) until they delete the local one. That is the
accepted cost of not holding the whole upgrade commit (#5443). No backup/merge
UX is introduced here.
"""

from __future__ import annotations

from pathlib import Path

from specify_cli.runtime.home import get_kittify_home

from ..registry import MigrationRegistry
from .base import BaseMigration, MigrationResult
from .m_0_9_1_complete_lane_migration import get_agent_dirs_for_project
from kernel.paths import to_posix

_VERSION_MARKER_PREFIX = "<!-- spec-kitty-command-version:"
_VERSION_MARKER_HEAD_LINES = 15

_HOLD = "hold"
_KEEP = "keep"
_REMOVE = "remove"


class _SafeGlobalizeCommandsBase(BaseMigration):
    """Shared safe command-cleanup behavior used by multiple upgrade paths."""

    @staticmethod
    def _iter_agent_command_dirs(project_path: Path) -> list[tuple[str, str]]:
        """Return candidate command dirs, including legacy Codex prompt roots."""
        agent_dirs = list(get_agent_dirs_for_project(project_path))
        legacy_codex_dir = project_path / ".codex" / "prompts"
        if legacy_codex_dir.is_dir():
            agent_dirs.append((".codex", "prompts"))
        return agent_dirs

    def detect(self, project_path: Path) -> bool:
        """Return True if any project-local spec-kitty command file exists."""
        for agent_root, subdir in self._iter_agent_command_dirs(project_path):
            agent_dir = project_path / agent_root / subdir
            if not agent_dir.is_dir():
                continue
            for candidate in agent_dir.iterdir():
                if candidate.name.startswith("spec-kitty."):
                    return True
        return False

    def can_apply(self, project_path: Path) -> tuple[bool, str]:
        return True, ""

    @staticmethod
    def _global_runtime_present() -> bool:
        """Return True when the user-global runtime tree is available."""
        try:
            missions_dir = get_kittify_home() / "missions"
        except Exception:
            return False
        if not missions_dir.is_dir():
            return False
        return any(p.is_dir() for p in missions_dir.iterdir())

    @staticmethod
    def _global_command_file_present(agent_root: str, subdir: str, filename: str) -> bool:
        """Check that the exact global replacement file exists."""
        try:
            global_agent_dir = Path.home() / agent_root / subdir
        except Exception:
            return False
        return (global_agent_dir / filename).is_file()

    @staticmethod
    def _is_generated_file(path: Path) -> bool:
        """Return True when the file head contains a spec-kitty version marker."""
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            return False
        for line in content.splitlines()[:_VERSION_MARKER_HEAD_LINES]:
            if line.strip().startswith(_VERSION_MARKER_PREFIX):
                return True
        return False

    @staticmethod
    def _rel(path: Path, project_path: Path) -> str:
        return to_posix(path.relative_to(project_path))

    def _preserve(
        self,
        *,
        changes: list[str],
        preserved_paths: list[str],
        rel: str,
        reason: str,
        dry_run: bool,
    ) -> None:
        verb = "Would preserve" if dry_run else "Preserved"
        changes.append(f"{verb}: {rel} ({reason})")
        preserved_paths.append(rel)

    def _classify(
        self,
        *,
        target: Path,
        agent_root: str,
        subdir: str,
        runtime_present: bool,
    ) -> tuple[str, str]:
        """Decide what to do with one project-local command file.

        Returns ``(action, reason)`` where *action* is ``"hold"`` (no version marker:
        operator-authored or unproven, held for manual review), ``"keep"`` (generated,
        but the global runtime or exact global replacement is absent) or ``"remove"``.
        The marker check comes first: only a missing marker means "customised".
        """
        if not self._is_generated_file(target):
            return _HOLD, "no version marker (user-authored or unproven file)"
        if not runtime_present:
            return _KEEP, "global runtime (~/.kittify/missions/) not found"
        if not self._global_command_file_present(agent_root, subdir, target.name):
            return _KEEP, f"no global equivalent at ~/{agent_root}/{subdir}/{target.name}"
        return _REMOVE, ""

    def apply(self, project_path: Path, dry_run: bool = False) -> MigrationResult:
        changes: list[str] = []
        warnings: list[str] = []
        preserved_paths: list[str] = []
        runtime_present = self._global_runtime_present()
        verb_keep = "Would keep" if dry_run else "Kept"

        for agent_root, subdir in self._iter_agent_command_dirs(project_path):
            agent_dir = project_path / agent_root / subdir
            if not agent_dir.is_dir():
                continue

            targets = sorted(candidate for candidate in agent_dir.iterdir() if candidate.name.startswith("spec-kitty."))
            for target in targets:
                rel = self._rel(target, project_path)
                action, reason = self._classify(target=target, agent_root=agent_root, subdir=subdir, runtime_present=runtime_present)
                if action == _HOLD:
                    self._preserve(
                        changes=changes,
                        preserved_paths=preserved_paths,
                        rel=rel,
                        reason=reason,
                        dry_run=dry_run,
                    )
                    continue
                if action == _KEEP:
                    changes.append(f"{verb_keep}: {rel} (generated; {reason})")
                    continue

                if dry_run:
                    changes.append(f"Would remove: {rel}")
                    continue

                try:
                    target.chmod(target.stat().st_mode | 0o222)
                    target.unlink()
                    changes.append(f"Removed: {rel}")
                except OSError as exc:
                    # Ours (it carries the marker), just not removable: kept, not held.
                    changes.append(f"Kept: {rel} (generated; unlink failed: {exc})")
                    warnings.append(f"Could not remove {rel}: {exc}")

            if not dry_run and agent_dir.is_dir():
                try:
                    agent_dir.rmdir()
                    changes.append(f"Removed empty directory: {self._rel(agent_dir, project_path)}")
                except OSError:
                    pass

        return MigrationResult(
            success=True,
            changes_made=changes,
            warnings=warnings,
            manual_review_required=bool(preserved_paths),
            preserved_paths=preserved_paths,
        )


@MigrationRegistry.register
class GlobalizeCommandsMigration(_SafeGlobalizeCommandsBase):
    """Safely remove per-project spec-kitty command files."""

    migration_id = "3.1.2_globalize_commands"
    description = "Safely remove per-project spec-kitty command files after global install"
    target_version = "3.1.2"
