"""Tests for ``specify_cli.doctrine.pack_assembler``."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest

from specify_cli.doctrine.pack_assembler import (
    AssemblyResult,
    assemble_pack,
    render_assembly_result,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


pytestmark = [pytest.mark.unit, pytest.mark.fast]

def _make_pack(
    root: Path,
    name: str,
    *,
    directives: list[str] | None = None,
) -> Path:
    """Create a minimal valid pack with the given directive IDs."""
    pack = root / name
    pack.mkdir(parents=True, exist_ok=True)
    if directives:
        dir_dir = pack / "directives"
        dir_dir.mkdir(parents=True, exist_ok=True)
        for artifact_id in directives:
            (dir_dir / f"{artifact_id.lower()}.directive.yaml").write_text(
                textwrap.dedent(
                    f"""\
                    schema_version: "1.0"
                    id: {artifact_id}
                    title: {artifact_id} title
                    intent: Generated by tests.
                    enforcement: advisory
                    """
                ),
                encoding="utf-8",
            )
    return pack


def _add_drg_fragment(
    pack: Path, name: str, *, source: str, target: str
) -> None:
    drg = pack / "drg"
    drg.mkdir(parents=True, exist_ok=True)
    (drg / name).write_text(
        textwrap.dedent(
            f"""\
            schema_version: "1.0"
            generated_at: STATIC
            generated_by: test
            nodes: []
            edges:
              - source: {source}
                target: {target}
                relation: requires
            """
        ),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Tests — happy paths
# ---------------------------------------------------------------------------


class TestAssemblePack:
    def test_single_pack(self, tmp_path: Path) -> None:
        pack = _make_pack(tmp_path, "alpha", directives=["A-001", "A-002", "A-003"])
        output = tmp_path / "out"

        result = assemble_pack([pack], output)

        assert isinstance(result, AssemblyResult)
        assert result.ok is True, result.errors
        assert result.artifacts_written == 3
        assert (output / "directives").is_dir()
        assert len(list((output / "directives").glob("*.directive.yaml"))) == 3
        assert (output / "pack-manifest.yaml").is_file()

    def test_two_packs_no_conflict(self, tmp_path: Path) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["A-001"])
        b = _make_pack(tmp_path, "bravo", directives=["B-001"])
        output = tmp_path / "out"

        result = assemble_pack([a, b], output)

        assert result.ok is True, result.errors
        assert result.artifacts_written == 2
        files = list((output / "directives").glob("*.directive.yaml"))
        assert {f.name for f in files} == {
            "a-001.directive.yaml",
            "b-001.directive.yaml",
        }

    def test_id_conflict_blocks(self, tmp_path: Path) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["DUP-001"])
        b = _make_pack(tmp_path, "bravo", directives=["DUP-001"])
        output = tmp_path / "out"

        result = assemble_pack([a, b], output)

        assert result.ok is False
        assert result.artifacts_written == 0
        assert result.conflicts, "expected at least one conflict"
        names = {pack for c in result.conflicts for pack in c.conflicting_packs}
        assert {"alpha", "bravo"}.issubset(names)
        assert not output.exists(), "output dir must not be created on conflict"

    def test_force_resolves_conflict(self, tmp_path: Path) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["DUP-002"])
        b = _make_pack(tmp_path, "bravo", directives=["DUP-002"])
        # Mutate bravo's file so we can verify last-pack-wins.
        bravo_file = b / "directives" / "dup-002.directive.yaml"
        bravo_file.write_text(
            textwrap.dedent(
                """\
                schema_version: "1.0"
                id: DUP-002
                title: BRAVO TITLE
                intent: From bravo.
                enforcement: advisory
                """
            ),
            encoding="utf-8",
        )
        output = tmp_path / "out"

        result = assemble_pack([a, b], output, force=True)

        assert result.ok is True, result.errors
        assert result.artifacts_written == 1
        produced = (output / "directives" / "dup-002.directive.yaml").read_text(
            encoding="utf-8"
        )
        assert "BRAVO TITLE" in produced

    def test_drg_conflict(self, tmp_path: Path) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["X-001", "X-002"])
        b = _make_pack(tmp_path, "bravo", directives=["Y-001", "Y-002"])
        # Same edge defined in both packs.
        _add_drg_fragment(
            a, "010.graph.yaml", source="directive:X-001", target="directive:X-002"
        )
        _add_drg_fragment(
            b, "010.graph.yaml", source="directive:X-001", target="directive:X-002"
        )
        output = tmp_path / "out"

        result = assemble_pack([a, b], output)

        assert result.ok is False
        drg_conflicts = [c for c in result.conflicts if c.artifact_type == "drg"]
        assert drg_conflicts, result.conflicts

    def test_force_dedup_prunes_duplicate_edges_via_canonical_serializer(
        self, tmp_path: Path
    ) -> None:
        """WP05/T020 (#3075, #2977): the force-dedup re-emit path used to build
        its pruned fragment via raw ``n.model_dump()`` / ``e.model_dump()``,
        bypassing ``model_to_graph_dict`` entirely. That dropped
        ``FIELDS_WITHHELD_FROM_GRAPH_OUTPUT`` (it emitted a literal
        ``provenance: null`` key the canonical writer withholds) in addition
        to the pre-existing duplicate-edge pruning behaviour this test also
        pins. Regression coverage for the ``_document_dict``-routed rewrite.
        """
        a = _make_pack(tmp_path, "alpha", directives=["X-101", "X-102"])
        b = _make_pack(tmp_path, "bravo", directives=["X-101", "X-102"])
        # Same edge defined in both packs -- force=True must keep exactly one.
        _add_drg_fragment(
            a, "010.graph.yaml", source="directive:X-101", target="directive:X-102"
        )
        _add_drg_fragment(
            b, "010.graph.yaml", source="directive:X-101", target="directive:X-102"
        )
        output = tmp_path / "out"

        result = assemble_pack([a, b], output, force=True)

        assert result.ok is True, result.errors
        fragments = sorted((output / "drg").glob("*.graph.yaml"))
        assert len(fragments) == 2, "one fragment per pack must survive, renumbered"

        rendered = [f.read_text(encoding="utf-8") for f in fragments]
        # The DUPLICATE edge itself (source+target+relation) must appear only
        # once across both re-emitted fragments -- the pruning behaviour this
        # path exists for.
        edge_block_count = sum(text.count("relation: requires") for text in rendered)
        assert edge_block_count == 1, (
            f"expected exactly one surviving duplicate edge, got {edge_block_count}:\n"
            + "\n---\n".join(rendered)
        )
        # The canonical serializer withholds `provenance` (FIELDS_WITHHELD_
        # FROM_GRAPH_OUTPUT); the old raw .model_dump() path emitted it as a
        # literal `provenance: null` key on every node/edge.
        assert not any("provenance" in text for text in rendered), (
            "pruned fragment(s) leaked the withheld `provenance` field -- "
            "force-dedup re-emit did not route through the canonical "
            f"document serializer:\n{rendered}"
        )

    def test_conflicts_out_written(self, tmp_path: Path) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["DUP-003"])
        b = _make_pack(tmp_path, "bravo", directives=["DUP-003"])
        output = tmp_path / "out"
        conflicts_out = tmp_path / "conflicts.json"

        result = assemble_pack(
            [a, b], output, conflicts_out=conflicts_out
        )

        assert result.ok is False
        assert conflicts_out.is_file()
        payload = json.loads(conflicts_out.read_text(encoding="utf-8"))
        assert isinstance(payload, list)
        assert payload, "conflicts JSON must be non-empty on conflict"
        assert payload[0]["artifact_id"] == "DUP-003"

    def test_assembled_pack_is_validated(self, tmp_path: Path) -> None:
        # When the merged pack would be invalid, the assembler must clean up
        # and return ok=False.  We simulate this by feeding in a pack whose
        # directive is *individually* valid but produces a dangling DRG edge
        # in the merged output.
        a = _make_pack(tmp_path, "alpha", directives=["Q-001"])
        _add_drg_fragment(
            a,
            "010.graph.yaml",
            source="directive:Q-001",
            target="directive:NEVER-DEFINED",
        )
        output = tmp_path / "out"

        result = assemble_pack([a], output)

        assert result.ok is False
        assert not output.exists()
        assert any("validation" in e for e in result.errors)

    def test_no_input_packs_is_error(self, tmp_path: Path) -> None:
        result = assemble_pack([], tmp_path / "out")
        assert result.ok is False
        assert "no input packs" in " ".join(result.errors).lower()

    def test_missing_input_pack_is_error(self, tmp_path: Path) -> None:
        ghost = tmp_path / "ghost"
        result = assemble_pack([ghost], tmp_path / "out")
        assert result.ok is False
        assert any("not found" in e for e in result.errors)

    def test_force_refuses_to_delete_non_pack_output_dir(
        self, tmp_path: Path
    ) -> None:
        pack = _make_pack(tmp_path, "alpha", directives=["SAFE-001"])
        output = tmp_path / "important-data"
        output.mkdir()
        marker = output / "do-not-delete.txt"
        marker.write_text("keep\n", encoding="utf-8")

        result = assemble_pack([pack], output, force=True)

        assert result.ok is False
        assert "refusing to delete non-pack" in " ".join(result.errors)
        assert marker.read_text(encoding="utf-8") == "keep\n"

    def test_force_refuses_spoofed_minimal_pack_manifest(
        self, tmp_path: Path
    ) -> None:
        pack = _make_pack(tmp_path, "alpha", directives=["SAFE-002"])
        output = tmp_path / "important-data"
        output.mkdir()
        (output / "pack-manifest.yaml").write_text(
            "source_type: assemble\n",
            encoding="utf-8",
        )
        marker = output / "do-not-delete.txt"
        marker.write_text("keep\n", encoding="utf-8")

        result = assemble_pack([pack], output, force=True)

        assert result.ok is False
        assert "refusing to delete non-pack" in " ".join(result.errors)
        assert marker.read_text(encoding="utf-8") == "keep\n"

    def test_force_recognises_fetched_artifactory_pack_manifest(
        self, tmp_path: Path
    ) -> None:
        pack = _make_pack(tmp_path, "alpha", directives=["NEW-ART-001"])
        output = tmp_path / "fetched-artifactory-pack"
        output.mkdir()
        (output / "pack-manifest.yaml").write_text(
            textwrap.dedent(
                """\
                artifact_counts: {}
                fetched_at: '2026-08-22T12:00:00Z'
                pack_version: 3.2.7
                source_type: artifactory
                source_url: https://artifactory.example.com/artifactory/repo/pack.tar.gz
                """
            ),
            encoding="utf-8",
        )
        marker = output / "old-artifact.txt"
        marker.write_text("old\n", encoding="utf-8")

        result = assemble_pack([pack], output, force=True)

        assert result.ok is True, result.errors
        assert not marker.exists()
        assert (output / "directives" / "new-art-001.directive.yaml").is_file()

    def test_force_allows_replacing_previous_pack_output(
        self, tmp_path: Path
    ) -> None:
        first = _make_pack(tmp_path, "alpha", directives=["OLD-001"])
        second = _make_pack(tmp_path, "bravo", directives=["NEW-001"])
        output = tmp_path / "out"

        first_result = assemble_pack([first], output)
        assert first_result.ok is True, first_result.errors

        second_result = assemble_pack([second], output, force=True)

        assert second_result.ok is True, second_result.errors
        assert not (output / "directives" / "old-001.directive.yaml").exists()
        assert (output / "directives" / "new-001.directive.yaml").exists()

    def test_internal_validate_pack_call_carves_out_drg_root_check(
        self, tmp_path: Path
    ) -> None:
        """FR-004 / AC-6 (operator ruling #2, ``reviews/plan.ruling.md``):
        ``assemble_pack``'s internal round-trip ``validate_pack(...)`` call
        passes ``check_drg_root=False`` — proven by an actual
        parameter-value assertion, not merely by
        ``test_force_dedup_prunes_duplicate_edges_via_canonical_serializer``
        continuing to pass. This carve-out is unconditional and structural:
        ``_copy_drg_fragments`` never writes a pack-root ``*.graph.yaml``, so
        the assembler's own output is always exactly the drg/-fragments-only
        shape this check would otherwise flag.

        Before this WP, ``validate_pack`` has no ``check_drg_root`` keyword
        parameter at all, so asserting it was passed with that value fails.
        """
        from unittest.mock import patch

        from specify_cli.doctrine.pack_validator import ValidationResult

        pack = _make_pack(tmp_path, "alpha", directives=["V-001"])
        output = tmp_path / "out"

        with patch(
            "specify_cli.doctrine.pack_assembler.validate_pack",
            return_value=ValidationResult(ok=True),
        ) as mock_validate:
            result = assemble_pack([pack], output)

        assert result.ok is True, result.errors
        mock_validate.assert_called_once_with(output, check_drg_root=False)


# ---------------------------------------------------------------------------
# Tests — rendering
# ---------------------------------------------------------------------------


class TestRenderAssemblyResult:
    def test_json_output_on_success(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        pack = _make_pack(tmp_path, "alpha", directives=["A-001"])
        output = tmp_path / "out"
        result = assemble_pack([pack], output)
        render_assembly_result(
            result,
            output_dir=output,
            input_packs=[pack],
            json_output=True,
        )
        payload = json.loads(capsys.readouterr().out.strip())
        assert payload["ok"] is True
        assert payload["artifacts_written"] == 1

    def test_human_output_on_conflict(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        a = _make_pack(tmp_path, "alpha", directives=["DUP-099"])
        b = _make_pack(tmp_path, "bravo", directives=["DUP-099"])
        output = tmp_path / "out"
        result = assemble_pack([a, b], output)
        render_assembly_result(
            result,
            output_dir=output,
            input_packs=[a, b],
            json_output=False,
        )
        out = capsys.readouterr().out
        assert "Conflict" in out
        assert "--force" in out
