"""Render a prepared pack skill into ``SKILL.md`` text (ADR 2026-09-27-1, FR-009).

A pack skill is a *thin* entry point: the rendered file carries a generated
preamble that fetches the governing doctrine at run time
(``spec-kitty charter context --include <urn>`` for every required URN) and
never inlines the procedure text itself (single canonical authority). No
run-time bindings are baked in and no ``allowed-tools`` key is ever emitted
(C-005 / FR-004).

The renderer is pure: :func:`render_pack_skill` takes the charter-side
:class:`~charter.activation.skill_preparation.PreparedSkill` and returns text.
A wrapper skill's ``builtin:`` target is validated here, against the canonical
command set the command-skill installer owns, so an unknown target is refused
before anything is staged or written.
"""

from __future__ import annotations

import json

from charter.activation.skill_preparation import BUILTIN_TARGET_PREFIX, CLI_TARGET_PREFIX, PreparedSkill
from specify_cli.skills.command_installer import CANONICAL_COMMANDS

__all__ = ["PackSkillRenderError", "render_pack_skill"]

#: Name of the built-in command skills a ``builtin:`` target points at.
_COMMAND_SKILL_PREFIX = "spec-kitty."

_GENERATED_NOTICE = "<!-- Generated by spec-kitty from a charter pack skill; edits are overwritten on the next projection. -->"


class PackSkillRenderError(ValueError):
    """A prepared pack skill cannot be rendered (unknown target, malformed body)."""


def render_pack_skill(prepared: PreparedSkill) -> str:
    """Return the ``SKILL.md`` text for *prepared*.

    Raises :class:`PackSkillRenderError` for a wrapper whose ``builtin:``
    target is not a canonical ``spec-kitty.<command>``.
    """
    sections = [
        _frontmatter(prepared),
        _GENERATED_NOTICE,
        f"# {prepared.skill.title}",
        _context_preamble(prepared.requires),
        _parameters_section(prepared),
        _instructions(prepared),
    ]
    return "\n\n".join(section for section in sections if section) + "\n"


def _quoted(value: str) -> str:
    """A JSON string is a valid double-quoted YAML scalar."""
    return json.dumps(value, ensure_ascii=False)


def _frontmatter(prepared: PreparedSkill) -> str:
    invocation = prepared.skill.invocation
    lines = [
        "---",
        f"name: {_quoted(prepared.rendered_name)}",
        f"description: {_quoted(_description(prepared))}",
        f"user-invocable: {str(invocation.user_invocable).lower()}",
    ]
    if not invocation.model_invocable:
        lines.append("disable-model-invocation: true")
    lines.append("---")
    return "\n".join(lines)


def _description(prepared: PreparedSkill) -> str:
    skill = prepared.skill
    description = " ".join(skill.description.split())
    if skill.triggers:
        description = f"{description} Triggers: {', '.join(skill.triggers)}."
    return description


def _context_preamble(requires: tuple[str, ...]) -> str:
    if not requires:
        return ""
    commands = "\n".join(f"- `spec-kitty charter context --include {urn}`" for urn in requires)
    return f"## Governing context\n\nBefore acting, load the doctrine this skill depends on:\n\n{commands}"


def _parameters_section(prepared: PreparedSkill) -> str:
    parameters = prepared.skill.parameters
    if not parameters:
        return ""
    lines = ["## Parameters", ""]
    for parameter in parameters:
        details = ["required" if parameter.required else "optional"]
        if parameter.default is not None:
            details.append(f"default `{parameter.default}`")
        suffix = f": {parameter.description}" if parameter.description else ""
        lines.append(f"- `{parameter.name}` ({', '.join(details)}){suffix}")
    return "\n".join(lines)


def _instructions(prepared: PreparedSkill) -> str:
    if prepared.form == "prompt":
        body = (prepared.body or "").replace("\r\n", "\n").replace("\r", "\n").strip()
        if not body:
            raise PackSkillRenderError(f"prompt-form skill {prepared.id!r} has an empty body")
        return f"## Instructions\n\n{body}"
    expansion = prepared.expansion
    if expansion is None:
        raise PackSkillRenderError(f"wrapper-form skill {prepared.id!r} has no expansion")
    return f"## Instructions\n\n{_wrapper_instruction(prepared.id, expansion.target, expansion.args)}"


def _wrapper_instruction(skill_id: str, target: str, args: str) -> str:
    arguments = f" Pass these arguments: `{args}`." if args else ""
    if target.startswith(BUILTIN_TARGET_PREFIX):
        command = _validated_command(skill_id, target.removeprefix(BUILTIN_TARGET_PREFIX))
        return f"Invoke the `{_COMMAND_SKILL_PREFIX}{command}` command skill.{arguments}"
    if target.startswith(CLI_TARGET_PREFIX):
        argv = target.removeprefix(CLI_TARGET_PREFIX).strip()
        return f"Run the CLI command:\n\n```bash\n{argv}{(' ' + args) if args else ''}\n```"
    raise PackSkillRenderError(f"wrapper skill {skill_id!r} has an unsupported target {target!r}")


def _validated_command(skill_id: str, name: str) -> str:
    """Return the canonical command named by ``spec-kitty.<command>``."""
    command = name.strip().removeprefix(_COMMAND_SKILL_PREFIX) if name.strip().startswith(_COMMAND_SKILL_PREFIX) else ""
    if command not in CANONICAL_COMMANDS:
        known = ", ".join(f"{_COMMAND_SKILL_PREFIX}{item}" for item in CANONICAL_COMMANDS)
        raise PackSkillRenderError(f"wrapper skill {skill_id!r} targets unknown built-in command {name!r}; known commands: {known}")
    return command
