"""The org-charter leg of pack validation and assembly cannot be skipped silently.

Mission ``charter-pack-cutover-01M491G6`` WP04 (#3732, research A.3 #4):
``validate_pack`` and ``assemble_pack`` live in ``charter.offering.packs`` and
take their org-charter leg as a hook (org charter composition is an activation
concern). These tests pin that

* a pack that ships ``org-charter.yaml`` with no hook is an explicit error
  (validate) or a refusal before anything is written (assemble);
* a supplied hook is called and its findings are sorted by severity;
* the CLI reaches the org-charter leg through the composing entries
  (``validate_pack_with_org_charter`` / ``assemble_pack_with_org_charter``).
"""

from __future__ import annotations

import textwrap
from collections.abc import Sequence
from collections.abc import Set as AbstractSet
from pathlib import Path

import pytest
import yaml
from typer.testing import CliRunner

from charter.offering.packs.pack_assembler import assemble_pack
from charter.offering.packs.pack_validator import (
    ORG_CHARTER_UNCHECKED_CATEGORY,
    ValidationIssue,
    validate_pack,
)
from specify_cli.cli.commands.charter import charter_app as app
from charter.activation import org_charter

pytestmark = [pytest.mark.unit, pytest.mark.fast]

runner = CliRunner()

_ORG_CHARTER = "org-charter.yaml"


def _pack(root: Path, name: str, *, charter: str | None, directive: str | None = "DIR-A") -> Path:
    pack = root / name
    pack.mkdir(parents=True)
    if directive is not None:
        (pack / "directives").mkdir()
        (pack / "directives" / f"{directive.lower()}.directive.yaml").write_text(
            textwrap.dedent(
                f"""\
                schema_version: "1.0"
                id: {directive}
                title: {directive} title
                intent: Generated by tests.
                enforcement: advisory
                """
            ),
            encoding="utf-8",
        )
    if charter is not None:
        (pack / _ORG_CHARTER).write_text(textwrap.dedent(charter), encoding="utf-8")
    return pack


_VALID_CHARTER = """\
    schema_version: "1"
    required_directives:
      - DIR-A
      - DIR-ELSEWHERE
    governance_policies:
      - field: review
        value: true
        enforcement: blocking
"""


def test_validate_pack_without_hook_reports_unchecked_org_charter(tmp_path: Path) -> None:
    pack = _pack(tmp_path, "p", charter=_VALID_CHARTER)

    result = validate_pack(pack)

    assert not result.ok
    unchecked = [issue for issue in result.errors if issue.category == ORG_CHARTER_UNCHECKED_CATEGORY]
    assert len(unchecked) == 1
    assert unchecked[0].file == str(pack / _ORG_CHARTER)
    assert "no checker supplied" in unchecked[0].message


def test_validate_pack_without_org_charter_needs_no_hook(tmp_path: Path) -> None:
    pack = _pack(tmp_path, "p", charter=None)

    result = validate_pack(pack)

    assert result.ok, [issue.message for issue in result.errors]


def test_validate_pack_calls_the_hook_and_sorts_findings_by_severity(tmp_path: Path) -> None:
    pack = _pack(tmp_path, "p", charter=_VALID_CHARTER)
    calls: list[tuple[Path, AbstractSet[str]]] = []

    def check(path: Path, directive_ids: AbstractSet[str]) -> list[ValidationIssue]:
        calls.append((path, directive_ids))
        return [
            ValidationIssue(severity="error", artifact_type="org-charter", artifact_id=None, file=str(path), message="hook error"),
            ValidationIssue(severity="advisory", artifact_type="org-charter", artifact_id=None, file=str(path), message="hook advisory"),
        ]

    result = validate_pack(pack, org_charter_check=check)

    assert calls == [(pack / _ORG_CHARTER, {"DIR-A"})]
    assert [issue.message for issue in result.errors] == ["hook error"]
    assert [issue.message for issue in result.advisories] == ["hook advisory"]


def test_validate_org_charter_file_reports_advisories(tmp_path: Path) -> None:
    pack = _pack(tmp_path, "p", charter=_VALID_CHARTER)

    issues = org_charter.validate_org_charter_file(pack / _ORG_CHARTER, frozenset({"DIR-A"}))

    assert {issue.severity for issue in issues} == {"advisory"}
    assert {issue.artifact_id for issue in issues} == {"review", "DIR-ELSEWHERE"}


@pytest.mark.parametrize(
    ("charter", "expected"),
    [
        ("key: [unclosed\n", "YAML parse error"),
        ("", "empty YAML document"),
        ("- a list\n", "expected a YAML mapping at top level"),
        ("required_directives: 7\n", "org-charter schema validation failed"),
    ],
)
def test_validate_org_charter_file_reports_errors(tmp_path: Path, charter: str, expected: str) -> None:
    pack = _pack(tmp_path, "p", charter=charter)

    issues = org_charter.validate_org_charter_file(pack / _ORG_CHARTER)

    assert len(issues) == 1
    assert issues[0].severity == "error"
    assert expected in issues[0].message


def test_assemble_pack_without_merge_refuses_before_writing(tmp_path: Path) -> None:
    a = _pack(tmp_path, "a", charter=_VALID_CHARTER)
    b = _pack(tmp_path, "b", charter=None, directive="DIR-B")
    out = tmp_path / "out"

    result = assemble_pack([a, b], out)

    assert not result.ok
    assert len(result.errors) == 1
    assert "org charter not merged: no merger supplied" in result.errors[0]
    assert str(a / _ORG_CHARTER) in result.errors[0]
    assert not out.exists()


def test_assemble_pack_runs_the_merge_and_check_legs(tmp_path: Path) -> None:
    a = _pack(tmp_path, "a", charter=_VALID_CHARTER)
    b = _pack(tmp_path, "b", charter=None, directive="DIR-B")
    out = tmp_path / "out"
    merged: list[list[Path]] = []
    checked: list[Path] = []

    def merge(paths: Sequence[Path], output_dir: Path) -> None:
        merged.append(list(paths))
        (output_dir / _ORG_CHARTER).write_text('schema_version: "1"\n', encoding="utf-8")

    def check(path: Path, _directive_ids: AbstractSet[str]) -> list[ValidationIssue]:
        checked.append(path)
        return []

    result = assemble_pack([a, b], out, org_charter_merge=merge, org_charter_check=check)

    assert result.ok, result.errors
    assert merged == [[a / _ORG_CHARTER]]
    assert checked == [out / _ORG_CHARTER]


def test_merge_org_charter_files_unions_and_dedupes(tmp_path: Path) -> None:
    a = _pack(
        tmp_path,
        "a",
        charter="""\
        schema_version: "1"
        interview_defaults: {lang: en, tone: plain}
        required_directives: [DIR-A, DIR-B]
        governance_policies:
          - {field: review, value: true}
        """,
    )
    b = _pack(
        tmp_path,
        "b",
        charter="""\
        interview_defaults: {lang: nl}
        required_directives: [DIR-B, DIR-C]
        governance_policies:
          - {field: review, value: true}
          - {field: tests, value: required}
        """,
    )
    broken = tmp_path / "broken.yaml"
    broken.write_text("- not a mapping\n", encoding="utf-8")
    out = tmp_path / "out"
    out.mkdir()

    org_charter.merge_org_charter_files([a / _ORG_CHARTER, broken, b / _ORG_CHARTER], out)

    data = yaml.safe_load((out / _ORG_CHARTER).read_text(encoding="utf-8"))
    assert data["interview_defaults"] == {"lang": "nl", "tone": "plain"}
    assert data["required_directives"] == ["DIR-A", "DIR-B", "DIR-C"]
    assert [(gp["field"], gp["value"]) for gp in data["governance_policies"]] == [("review", True), ("tests", "required")]


def test_merge_org_charter_files_writes_nothing_for_an_invalid_merge(tmp_path: Path) -> None:
    a = _pack(tmp_path, "a", charter="governance_policies:\n  - {field: review}\n")
    out = tmp_path / "out"
    out.mkdir()

    org_charter.merge_org_charter_files([a / _ORG_CHARTER], out)

    assert not (out / _ORG_CHARTER).exists()


def _sentinel_check(path: Path, _directive_ids: AbstractSet[str] = frozenset()) -> list[ValidationIssue]:
    return [ValidationIssue(severity="error", artifact_type="org-charter", artifact_id=None, file=str(path), message="SENTINEL org-charter leg ran")]


@pytest.mark.parametrize("command", [["pack", "validate"], ["org", "validate"]])
def test_cli_validation_reaches_the_org_charter_leg(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, command: list[str]) -> None:
    pack = _pack(tmp_path, "p", charter=_VALID_CHARTER)
    monkeypatch.setattr(org_charter, "validate_org_charter_file", _sentinel_check)

    result = runner.invoke(app, [*command, str(pack)])

    assert result.exit_code == 1, result.output
    assert "SENTINEL org-charter leg ran" in result.output
    assert "no checker supplied" not in result.output


def test_cli_assembly_reaches_the_org_charter_legs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    a = _pack(tmp_path, "a", charter=_VALID_CHARTER)
    out = tmp_path / "out"
    monkeypatch.setattr(org_charter, "validate_org_charter_file", _sentinel_check)

    result = runner.invoke(app, ["pack", "assemble", str(out), str(a)])

    assert result.exit_code == 1, result.output
    assert "SENTINEL org-charter leg ran" in result.output
    assert "no merger supplied" not in result.output
