"""Shared fixtures for tasks integration tests."""

from __future__ import annotations

import json
import subprocess
from kernel.clock import now_utc_iso
from pathlib import Path

import pytest
from ulid import ULID

from specify_cli.lanes.branch_naming import _mid8, strip_numeric_prefix
from tests.conftest import reset_spec_kitty_queue_state


@pytest.fixture(autouse=True)
def _disable_saas_sync_for_tasks_tests(monkeypatch: pytest.MonkeyPatch) -> None:
    """Disable the SaaS sync boundary preflight for tasks-suite tests.

    The root conftest enables SPEC_KITTY_ENABLE_SAAS_SYNC=1 so legacy
    sync/auth tests stay live, but these tasks-suite tests exercise
    finalize-tasks / setup-plan against a real developer queue state and
    the boundary preflight (FR-002 / FR-009) refuses on any legacy rows
    in scope. The preflight is not what these tests are testing — they
    test the planning workflow logic — so we disable the gate here.
    """
    monkeypatch.setenv("SPEC_KITTY_ENABLE_SAAS_SYNC", "0")


@pytest.fixture(autouse=True)
def _autoclean_spec_kitty_queue():
    """Wipe ``~/.spec-kitty/{queue.db,queues,daemon}`` before every test.

    Defense in depth on top of ``_disable_saas_sync_for_tasks_tests``:
    even if some test re-sets ``SPEC_KITTY_ENABLE_SAAS_SYNC=1`` for its
    own scope, the queue is empty so the preflight gate (upstream commit
    ``cc5e1ca9``) cannot refuse on cross-test pollution. Same wipe runs
    on teardown so tests in this tree do not leak pollution downstream.
    Mirrors JUnit's ``@Before``/``@After`` reset.
    """
    reset_spec_kitty_queue_state()
    yield
    reset_spec_kitty_queue_state()


def create_mission_fast(project: Path, slug: str, number: int = 1) -> Path:
    """Create a post-spec mission in-process, bypassing CLI subprocess overhead.

    Replicates the essential file structure downstream planning tests need
    after the specify phase: spec.md is already populated, committed, and
    substantive enough for setup-plan's entry gate. Suitable for use as
    **test setup** — not for testing the create command itself. Saves ~1 s per
    call by avoiding a full Python subprocess startup.
    """
    mission_id = str(ULID())
    human_slug = strip_numeric_prefix(slug)
    mission_slug = f"{human_slug}-{_mid8(mission_id)}"
    feature_dir = project / "kitty-specs" / mission_slug

    # Directory structure
    feature_dir.mkdir(parents=True, exist_ok=True)
    (feature_dir / "checklists").mkdir(exist_ok=True)
    (feature_dir / "research").mkdir(exist_ok=True)
    # contracts/ is a mission artifact → under the feature dir, not repo root (#2115)
    (feature_dir / "contracts").mkdir(exist_ok=True)
    for dirname in ("src", "tests", "docs"):
        (project / dirname).mkdir(exist_ok=True)
    tasks_dir = feature_dir / "tasks"
    tasks_dir.mkdir(exist_ok=True)

    # spec.md: setup-plan requires this to be committed and substantive.
    (feature_dir / "spec.md").write_text(
        f"""# {slug.replace('-', ' ').title()}

## Functional Requirements

| ID | Requirement | Acceptance Criteria | Status |
| --- | --- | --- | --- |
| FR-001 | {slug.replace('-', ' ').title()} has a planned implementation path. | The planning workflow creates and commits a valid plan. | proposed |
""",
        encoding="utf-8",
    )

    # meta.json
    meta = {
        "mission_id": mission_id,
        "mission_number": None,
        "slug": mission_slug,
        "mission_slug": mission_slug,
        "friendly_name": slug.replace("-", " "),
        "mission_type": "software-dev",
        "target_branch": "main",
        "created_at": now_utc_iso(),
    }
    (feature_dir / "meta.json").write_text(
        json.dumps(meta, indent=2) + "\n",
        encoding="utf-8",
    )

    # tasks/README.md + .gitkeep
    (tasks_dir / "README.md").write_text(
        "# Work Packages\n\nGenerated by spec-kitty.\n",
        encoding="utf-8",
    )
    (tasks_dir / ".gitkeep").touch()

    # Empty event log
    (feature_dir / "status.events.jsonl").touch()

    # Single git add + commit (much faster than a CLI subprocess)
    subprocess.run(
        ["git", "add", str(feature_dir)],
        cwd=project,
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "commit", "-m", f"Add spec for mission {mission_slug}"],
        cwd=project,
        check=True,
        capture_output=True,
    )

    return feature_dir
