"""Pre-commit hook installer for worktrees.

Installs a Python-based pre-commit hook that invokes the commit guard.
The generated hook pins the absolute Python interpreter path at install time
and does not depend on PATH (FR-009, C-003).

**Issue #254 — the pin can go stale.** An install-method migration (e.g. pipx
-> uv) moves the interpreter the hook pinned; the old path is simply gone on
the next commit, and the failure surfaces as a shell-level ``No such file or
directory`` naming a path rather than a cause. The generated hook therefore
falls back, at run time, to :data:`FALLBACK_COMMAND` (the ``spec-kitty``
console script) resolved fresh off ``PATH`` — install-agnostic by
construction, since it is whatever the CURRENT install put there, not a path
captured at some earlier install time. Only if BOTH the pinned interpreter and
the PATH fallback are unavailable does the hook fail, and then with a named
remedy (:func:`specify_cli.cli.commands.migrate_cmd.repin_hooks`) instead of a
bare path. See ``docs/adr/3.x/2026-08-27-1-precommit-hook-stable-entrypoint-and-repin-migration.md``.
"""

from __future__ import annotations

import os
import sys
import tempfile
from contextlib import suppress
from dataclasses import dataclass
from kernel.clock import now_utc_seconds
from pathlib import Path

from specify_cli.asset_preservation.backup import backup_before_overwrite

#: The install-agnostic fallback entrypoint (issue #254). Whatever install
#: method (pipx, uv tool install, ...) put a working ``spec-kitty`` on PATH,
#: this resolves it FRESH at hook run time rather than at hook install time —
#: unlike the pinned interpreter, it self-heals across an install migration.
FALLBACK_COMMAND = "spec-kitty"
#: Hidden CLI entrypoint (``cli/commands/commit_guard_hook_cmd.py``) the
#: fallback invokes — the same guard the pinned interpreter runs via
#: ``-m specify_cli.policy.commit_guard_hook``.
FALLBACK_SUBCOMMAND = "commit-guard-hook"
#: The repair command named in the hook's own failure message when neither
#: the pinned interpreter nor the PATH fallback is available.
REPIN_COMMAND = f"{FALLBACK_COMMAND} migrate repin-hooks"

HOOK_TEMPLATE = """\
#!/bin/sh
# Generated by spec-kitty. Do not edit by hand.
# Installed: {installed_at}
# Interpreter: {interpreter}
set -e
if [ -x "{interpreter}" ]; then
    exec "{interpreter}" -m specify_cli.policy.commit_guard_hook "$@"
fi
if command -v {fallback_command} >/dev/null 2>&1; then
    exec {fallback_command} {fallback_subcommand} "$@"
fi
echo "[spec-kitty guard] Pinned interpreter is gone: {interpreter}" >&2
echo "[spec-kitty guard] '{fallback_command}' is also not on PATH." >&2
echo "[spec-kitty guard] Remedy: run '{repin_command}' from an environment where {fallback_command} is installed and on PATH." >&2
exit 1
"""

MODULE = "specify_cli.policy.commit_guard_hook"
SHEBANG = "#!/bin/sh"
HOOK_MODE = 0o700

#: The signature line ``install()`` writes into every hook it generates
#: (see ``HOOK_TEMPLATE`` above). Ownership detection (#4895) mirrors the
#: removal-direction proof in ``upgrade/migrations/m_2_0_0_retire_git_hooks.py``:
#: a plain substring check on rendered content, not a prover.
SPEC_KITTY_HOOK_SIGNATURE = "# Generated by spec-kitty."


@dataclass(frozen=True)
class HookInstallRecord:
    """Record of a successful pre-commit hook installation (data-model E-05)."""

    hook_path: Path
    interpreter: Path
    module: str
    shebang: str
    mode: int
    #: Sidecar path of a foreign (non-spec-kitty) pre-existing hook that was
    #: backed up before being overwritten (#4895), or ``None`` when no backup
    #: was needed (no pre-existing hook, or the pre-existing hook already
    #: bore the spec-kitty signature).
    backup_path: Path | None = None


def _is_spec_kitty_hook(hook_path: Path) -> bool:
    """Return ``True`` when ``hook_path``'s content bears the spec-kitty signature.

    A read failure (broken symlink, permission denial, undecodable bytes
    treated leniently) is treated as "not ours" — foreign until proven
    otherwise — so the backup-before-overwrite path fires rather than
    silently discarding content spec-kitty did not write.
    """
    try:
        content = hook_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return SPEC_KITTY_HOOK_SIGNATURE in content


def _backup_foreign_hook_if_present(hook_path: Path) -> Path | None:
    """Back up ``hook_path`` before it is overwritten, unless it is absent or spec-kitty-owned.

    No pre-existing hook (regular file or symlink, including a broken one)
    ⇒ ``None``, unchanged behaviour. A hook already bearing the spec-kitty
    signature ⇒ ``None``, replaced with no backup churn. Otherwise the
    foreign hook is backed up via the shared WP01 helper *before* the
    caller's ``os.replace`` — never after (#4895).
    """
    if not (hook_path.exists() or hook_path.is_symlink()):
        return None
    if _is_spec_kitty_hook(hook_path):
        return None
    return backup_before_overwrite(hook_path)


def install(repo_root: Path) -> HookInstallRecord:
    """Install pre-commit hook into a repository, pinning the absolute interpreter.

    Captures ``sys.executable`` at install time so the generated hook does not
    rely on ``python``, ``python3``, or ``py`` being on PATH.  The hook is
    written atomically (temp-file + ``os.replace``) with mode ``0o700`` and
    LF line endings.

    Symlinks in ``sys.executable`` are intentionally **not** resolved. Pipx,
    ``venv``, and ``virtualenv`` rely on Python being launched via the venv's
    ``bin/python`` symlink so site initialization sets ``sys.prefix`` to the
    venv and adds the venv's ``site-packages`` to ``sys.path``. Resolving the
    symlink to the underlying interpreter would strip that context and make
    ``specify_cli`` unimportable from the hook (issue #669).

    Args:
        repo_root: Path to the root of the git repository (must contain ``.git``).

    Returns:
        A :class:`HookInstallRecord` describing the installed hook.

    Raises:
        RuntimeError: If ``sys.executable`` does not refer to an existing file.
    """
    interpreter = Path(os.path.abspath(sys.executable))
    if not interpreter.is_file():
        raise RuntimeError(
            f"Cannot install pre-commit hook: sys.executable={sys.executable!r} "
            f"(absolute: {interpreter}) does not exist."
        )

    installed_at = now_utc_seconds()
    rendered = HOOK_TEMPLATE.format(
        installed_at=installed_at,
        interpreter=str(interpreter),
        fallback_command=FALLBACK_COMMAND,
        fallback_subcommand=FALLBACK_SUBCOMMAND,
        repin_command=REPIN_COMMAND,
    )

    hooks_dir = repo_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"

    fd, tmp_path_str = tempfile.mkstemp(prefix="pre-commit.", dir=str(hooks_dir))
    backup_path: Path | None = None
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(rendered)
        os.chmod(tmp_path_str, HOOK_MODE)
        # #4895: back up a foreign (non-spec-kitty) pre-existing hook BEFORE
        # the atomic replace below -- os.replace() does not follow a
        # symlink at the destination, so this still swaps the *link itself*
        # atomically once the backup has captured what was there.
        backup_path = _backup_foreign_hook_if_present(hook_path)
        os.replace(tmp_path_str, str(hook_path))
    except Exception:
        with suppress(OSError):
            os.unlink(tmp_path_str)
        raise

    return HookInstallRecord(
        hook_path=hook_path,
        interpreter=interpreter,
        module=MODULE,
        shebang=SHEBANG,
        mode=HOOK_MODE,
        backup_path=backup_path,
    )


def install_commit_guard(_worktree_path: Path, repo_root: Path) -> HookInstallRecord | None:
    """Install pre-commit hook into a worktree.

    Resolves the worktree's git hooks directory and installs the hook there.
    For worktrees, the ``.git`` file points to the worktree-specific git dir,
    so we use the repo_root's ``.git`` directory directly (which is the main
    repo hooks dir shared across all worktrees).

    This is the legacy entrypoint retained for callers that pass both
    ``worktree_path`` and ``repo_root``.  New code should call :func:`install`
    directly with the repository root.

    Args:
        worktree_path: Path to the worktree (unused; retained for API compat).
        repo_root: Path to the main repository root.

    Returns:
        The :class:`HookInstallRecord` (whose ``backup_path`` is set when a
        foreign pre-existing hook was preserved, #4895), or ``None`` on a
        genuine install failure. ``record.hook_path`` gives the installed
        hook path, matching the prior ``Path``-only return for read sites
        that only need the path.

    Note:
        Narrowed from a blanket ``except Exception: return None`` (#4895):
        only :class:`RuntimeError` (missing pinned interpreter) and
        :class:`OSError` (the family covering every disk-I/O failure
        ``install()``/``backup_before_overwrite`` can raise, including
        ``FileExistsError``) are treated as best-effort install failures.
        Any other exception propagates instead of silently discarding a
        backup that was already performed.
    """
    try:
        return install(repo_root)
    except (RuntimeError, OSError):
        return None
