"""Installs the lane work-tip recorder hooks (``contracts/lane-work-tip.md``).

A SEPARATE installer from :mod:`specify_cli.policy.hook_installer` (WP07 /
plan.md M5): the pre-commit ownership guard that module installs is a
Python-backed hook that pins an interpreter path and, on a foreign hook,
backs the foreign content up before overwriting it. The lane-tip recorder is
the opposite shape on both counts:

* It is a tiny, dependency-free POSIX ``sh`` script (NFR-001 -- it must never
  start a Python interpreter, which costs ~1.3s and would blow the 50ms
  budget).
* It installs into an empty slot, or a slot that already carries ITS OWN
  signature (idempotent re-install) -- never into a slot occupied by a
  foreign hook. A foreign hook is left byte-for-byte untouched, with a single
  warning (C-010, charter "User Customization Preservation") -- no backup
  file is written, because nothing is overwritten.

Installed into BOTH ``post-commit`` (fires on an ordinary lane commit) and
``post-rewrite`` (fires after ``git commit --amend``, ``git rebase``, and
``git cherry-pick`` re-attach HEAD -- plan.md M4). The hooks dir is resolved
via ``git rev-parse --git-path hooks`` so a repository-level
``core.hooksPath`` override, and a linked worktree's shared common hooks
dir, are both honored (unlike :mod:`hook_installer`, which hardcodes
``repo_root/.git/hooks``).
"""

from __future__ import annotations

import os
import subprocess
import tempfile
from contextlib import suppress
from pathlib import Path

from specify_cli.cli.console import console

__all__ = ["install_lane_tip_recorder", "pending_hook_names"]

#: The signature line every hook this installer writes carries. Distinct
#: from :data:`specify_cli.policy.hook_installer.SPEC_KITTY_HOOK_SIGNATURE`
#: (that module's pre-commit guard is a different hook slot with its own
#: ownership marker) -- this one names the lane-tip recorder specifically so
#: the two installers' ownership checks can never cross-recognize each
#: other's hook as their own.
LANE_TIP_HOOK_SIGNATURE = "# Generated by spec-kitty (lane-tip recorder)."

#: The exact hook body from ``contracts/lane-work-tip.md``. Installed
#: verbatim into both ``post-commit`` and ``post-rewrite`` -- the same script
#: answers both triggers: it only cares about the CURRENT ``HEAD`` at the
#: moment it runs, which is already the lane branch's new tip by the time
#: either hook fires (a rebase/amend/cherry-pick has finished re-attaching
#: HEAD before ``post-rewrite`` runs).
#:
#: ``id=${b##*-lane-}`` strips up to and including the LAST ``-lane-``
#: occurrence (plan.md M4): a mission slug that itself embeds ``-lane-``
#: (e.g. a recut branch ``kitty/mission-foo-lane-recut-01ABC``) still
#: resolves to the real trailing lane-id fragment, not a false match on the
#: embedded substring. The case guard then requires that fragment to be
#: non-empty and all-lowercase-ASCII (the lane-id grammar,
#: ``branch_naming._LANE_ID_RE``) -- ``recut-01ABC`` fails it and the hook
#: exits 0 without recording anything.
_HOOK_BODY = f"""\
#!/bin/sh
{LANE_TIP_HOOK_SIGNATURE} Do not edit by hand.
b=$(git symbolic-ref -q HEAD) || exit 0
case "$b" in refs/heads/kitty/mission-*-lane-*) ;; *) exit 0 ;; esac
id=${{b##*-lane-}}
case "$id" in ''|*[!a-z]*) exit 0 ;; esac
git update-ref "refs/spec-kitty/lane-tip/${{b#refs/heads/}}" HEAD >/dev/null 2>&1
exit 0
"""

_HOOK_NAMES = ("post-commit", "post-rewrite")
_HOOK_MODE = 0o755


def _git_out(repo_root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _resolve_hooks_dir(repo_root: Path) -> Path:
    """Resolve the effective hooks dir via ``git rev-parse --git-path hooks``.

    Honors ``core.hooksPath`` (returned verbatim, relative to ``repo_root``,
    when set) and a linked worktree's shared common hooks dir (returned
    already absolute in that case). ``git rev-parse`` prints the path
    relative to the CURRENT directory otherwise, so a relative result is
    joined onto ``repo_root`` (the ``cwd`` this runs with) rather than the
    process's own unrelated working directory.
    """
    hooks_dir = Path(_git_out(repo_root, "rev-parse", "--git-path", "hooks"))
    if hooks_dir.is_absolute():
        return hooks_dir
    return repo_root / hooks_dir


def _hooks_path_configured(repo_root: Path) -> bool:
    result = subprocess.run(
        ["git", "config", "--get", "core.hooksPath"],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0 and bool(result.stdout.strip())


def _working_tree_roots(repo_root: Path) -> list[Path]:
    """The working trees whose contents a hooks dir must not live in."""
    roots = [Path(_git_out(repo_root, "rev-parse", "--show-toplevel")).resolve()]
    common = Path(_git_out(repo_root, "rev-parse", "--git-common-dir"))
    if not common.is_absolute():
        common = repo_root / common
    roots.append(common.resolve().parent)
    return roots


def _installable_hooks_dir(repo_root: Path) -> tuple[Path | None, str]:
    """Resolve the hooks dir to install into, or ``(None, reason)`` to skip.

    Installs only into a real hooks directory that is NOT inside a working
    tree: a user-owned tracked hooks dir (husky ``.husky``, ``.githooks``)
    must never be written to (it dirties the checkout and spreads to
    collaborators), and a configured ``core.hooksPath`` that is not an
    existing directory (``/dev/null``, a typo) is never created.
    """
    hooks_dir = _resolve_hooks_dir(repo_root)
    if _hooks_path_configured(repo_root):
        if not hooks_dir.is_dir():
            return None, f"core.hooksPath resolves to {hooks_dir}, which is not a directory"
        resolved = hooks_dir.resolve()
        common_git_dir = Path(_git_out(repo_root, "rev-parse", "--git-common-dir"))
        if not common_git_dir.is_absolute():
            common_git_dir = repo_root / common_git_dir
        in_git_dir = resolved.is_relative_to(common_git_dir.resolve())
        if not in_git_dir and any(resolved.is_relative_to(root) for root in _working_tree_roots(repo_root)):
            return None, f"core.hooksPath resolves to {hooks_dir}, which is inside the working tree"
    return hooks_dir, ""


def _is_lane_tip_hook(hook_path: Path) -> bool:
    """True iff ``hook_path``'s content bears the lane-tip recorder's signature.

    A read failure (broken symlink, permission denial, undecodable bytes
    treated leniently) is treated as "foreign" -- never proven-ours, so the
    caller skips rather than overwrites (C-010).
    """
    try:
        content = hook_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return LANE_TIP_HOOK_SIGNATURE in content


def _install_one_hook(hooks_dir: Path, name: str) -> Path | None:
    """Install (or idempotently re-install) one hook slot.

    Returns the installed hook's path, or ``None`` when a foreign hook
    already occupies the slot -- the caller warns once per skipped slot and
    leaves the foreign content byte-for-byte untouched (no backup, no
    overwrite: this installer never goes through
    :mod:`specify_cli.policy.hook_installer`'s backup-and-overwrite path).
    """
    hook_path = hooks_dir / name
    if (hook_path.exists() or hook_path.is_symlink()) and not _is_lane_tip_hook(hook_path):
        return None

    fd, tmp_path_str = tempfile.mkstemp(prefix=f"{name}.", dir=str(hooks_dir))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(_HOOK_BODY)
        os.chmod(tmp_path_str, _HOOK_MODE)
        os.replace(tmp_path_str, str(hook_path))
    except OSError:
        with suppress(OSError):
            os.unlink(tmp_path_str)
        raise
    return hook_path


def pending_hook_names(repo_root: Path) -> list[str]:
    """Return the hook slot names (out of ``post-commit``/``post-rewrite``) still empty.

    A read-only, non-mutating probe (issue: the upgrade migration's
    ``detect()`` needs to know whether installing would DO anything, without
    calling :func:`install_lane_tip_recorder` itself). A slot occupied by a
    foreign hook is NOT "pending" -- this installer will never touch it, so
    counting it would make the migration detect forever even though there is
    nothing more it could ever do. Only a genuinely empty slot is pending.
    """
    try:
        hooks_dir, _reason = _installable_hooks_dir(repo_root)
    except subprocess.CalledProcessError:
        # Not (yet) a git repository -- nothing for this installer to do.
        return []
    if hooks_dir is None:
        return []
    return [name for name in _HOOK_NAMES if not (hooks_dir / name).exists() and not (hooks_dir / name).is_symlink()]


def install_lane_tip_recorder(repo_root: Path) -> list[Path]:
    """Install the lane-tip recorder into ``post-commit`` and ``post-rewrite``.

    Idempotent: re-running this against an already-installed pair rewrites
    them with byte-identical content and returns both paths again. A slot
    occupied by a genuinely foreign (non-lane-tip) hook is skipped with a
    single warning, its bytes left untouched (C-010) -- it is not counted in
    the returned list.

    Args:
        repo_root: The repository root (or a linked worktree's root -- the
            hooks dir this resolves to is the shared common dir either way).

    Returns:
        The paths of the hook slots actually written (0, 1, or 2 entries).
    """
    try:
        hooks_dir, reason = _installable_hooks_dir(repo_root)
        if hooks_dir is None:
            console.print(f"[yellow]⚠ Skipping lane-tip recorder install: {reason}.[/yellow]")
            return []
        hooks_dir.mkdir(parents=True, exist_ok=True)
        return _install_all(hooks_dir)
    except (OSError, subprocess.CalledProcessError) as exc:
        console.print(f"[yellow]⚠ Skipping lane-tip recorder install: {exc}.[/yellow]")
        return []


def _install_all(hooks_dir: Path) -> list[Path]:

    installed: list[Path] = []
    for name in _HOOK_NAMES:
        written = _install_one_hook(hooks_dir, name)
        if written is None:
            console.print(
                f"[yellow]⚠ {hooks_dir / name} is not spec-kitty-managed; "
                "skipping lane-tip recorder install for this hook (its "
                "content is left untouched). Lane work-tip recording will "
                "only happen at spec-kitty's own lane touches until this "
                "hook is spec-kitty-managed.[/yellow]"
            )
            continue
        installed.append(written)
    return installed
