"""Shard-identity roster for the nightly ``interpreter-matrix`` split (#4951, FR-016).

The single, always-timing-out ``interpreter-matrix`` job in
``ci-nightly.yml`` is replaced by N independent ``interpreter-matrix-shard-<N>``
jobs, each running a disjoint slice of ``pytest -m "fast or unit"`` on Python
3.13. This module is the SINGLE SOURCE OF TRUTH for shard identity: which
job keys exist, which test paths each one owns, and which ``--suite-key``
each shard's escalation call must use.

``tests/architectural/test_interpreter_shard_coverage.py`` reads
:data:`INTERPRETER_SHARDS` to:

1. Prove the union of every shard's real collected node-ids equals the full
   ``fast or unit`` 3.13 selection, with zero duplicates and zero gaps
   (FR-004/NFR-002).
2. Diff this roster's declared job keys against ``ci-nightly.yml``'s real
   ``jobs:`` keys, so a shard silently dropped from the job list (while
   remaining declared here) is a loud, named failure (FR-016) -- distinct
   from a shard that is present in the job list but collects 0 tests
   (FR-005).

``tests/architectural/test_performance_marker_guard.py`` also imports
:data:`INTERPRETER_SHARDS`/``INTERPRETER_SHARD_JOB_KEYS`` from here (dynamic
discovery, not a second hardcoded literal list) so shard identity is never
declared in more than one place.

Relationship to #5201's registry-derived lane (landing pass #5244,
LAND-PAT-007): these shards are an INTERPRETER-AXIS lane over ALL of
``fast or unit`` on Python 3.13, orthogonal to and independent of
``.github/ci-module-registry.yml``'s ``out_of_matrix_test_dirs``; their
overlap with the ``specify-cli-out-of-matrix`` job's ``tests/specify_cli``
subtrees (which run on the default interpreter instead) is intentional
complementary-interpreter coverage, not a double-run.

**REAL boundaries (NFR-006), derived from run 1's measurement (2026-09-27,
workflow_dispatch run 36294808024 on `ubuntu-24.04`, mode=full):**

- Shards 1-2 (`tests/unit tests/status tests/cli` /
  `tests/specify_cli/runtime tests/charter tests/kernel`) are UNCHANGED from
  the initial placeholder guess -- run 1 measured their real "Run fast/unit
  suite" step wall-clock directly: shard 1 = 351s (2203 collected), shard 2 =
  639s (3538 collected). Both comfortably fit a real budget.
- The initial placeholder shard 3 ("everything else", 29710 collected tests)
  was run 1's SMOKING GUN: its "Run fast/unit suite" step ran 46m19s (2779s)
  and its JOB-LEVEL conclusion was `cancelled` at the 45-minute cap -- a
  badly-imbalanced partition exactly as plan.md SS B anticipated. It is
  therefore split further, here, into 4 new shards (3-6) using a FRESH local
  `pytest --collect-only -q -m "fast or unit"` capture of that same
  "everything else" scope (29710 real node-ids, one collection call,
  2026-09-27), bucketed by top-level `tests/<dir>` (or `tests/specify_cli/<dir>`
  one level deeper, since `tests/specify_cli` alone was 14155/29710 -- 40%
  of the remaining total, too coarse a single unit), then partitioned into 4
  bins via a **simple greedy largest-first-to-smallest-bin (LPT) pass over
  this ONE fresh, real count list** -- this is NOT ledger SK-247's rejected
  mechanism: SK-247's defect is a COMMITTED duration list paired
  POSITIONALLY with node ids that goes stale as the suite changes and is
  never re-verified against a live recount; this partition is a ONE-TIME,
  human-reviewed grouping computed directly from a fresh collection in the
  SAME session that authors it, with no committed/stale duration file
  anywhere in this mechanism, and the coverage-completeness test
  (`test_interpreter_shard_coverage.py`) independently re-verifies, on every
  run, that the roster's declared paths still union to exactly the live full
  selection -- so even if the suite's directories drift after this roster is
  written, a real gap or overlap is caught immediately rather than silently
  trusted. Bins came out to 7428/7428/7427/7427 collected tests -- within 1
  test of perfectly even.
- Reproduction (corrected, landing pass #5244, LAND-PAT-005): no committed
  script performs this partition end-to-end -- `tracer-design-decisions.md`'s
  "Shard boundary redraw (T009)" section describes the METHOD in PROSE only
  ("generated by a one-off script", never itself committed or named by path).
  To regenerate this split by hand: (1) `pytest --collect-only -q -m "fast or
  unit" tests --ignore=<shard-1-paths> --ignore=<shard-2-paths>` to reproduce
  the "everything else" scope's real node-ids; (2) bucket those node-ids by
  top-level `tests/<dir>` (one level deeper, `tests/specify_cli/<dir>`, for
  any bucket too coarse to balance against); (3) feed each bucket's
  collected-test COUNT (not duration -- this partition balances test
  *counts*, never a duration list, which is exactly what ledger SK-247's
  rejected mechanism did) into
  `test_module_shard_registry.py::_lpt_bin_pack`, the SAME greedy
  largest-first-to-smallest-bin (LPT) algorithm this redraw used, into as
  many bins as new shards are wanted. `_lpt_bin_pack` takes `list[float]`, so
  pass bucket sizes as floats. Re-verify the result the same way this roster
  is continuously re-verified: `test_interpreter_shard_coverage.py`'s
  coverage-completeness test independently proves, on every run, that the
  roster's declared paths still union to exactly the live full selection --
  so a stale or mis-bucketed regeneration is a loud, named CI failure, not a
  silently trusted one.

Per-shard `timeout-minutes` (landing pass #5244, LAND-PAT-005; re-derived
#5378): the actual values live in ONE place -- each shard job's own
`timeout-minutes:` key in `ci-nightly.yml` -- and are deliberately NOT
restated here, so this docstring can never drift from the committed
workflow. The recorded derivation (measured maximum suite wall-clock, the
runs it came from, and the headroom formula) is the structured
`# headroom (#5378)` comment directly above each `timeout-minutes:` line in
`ci-nightly.yml`; `tests/ci/test_nightly_timeout_headroom.py` fails if a cap
falls below its own comment's formula.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable

# The ``job_key`` prefix every shard in this roster must follow --
# ``interpreter-matrix-shard-<N>``. Landing pass #5244 (LAND-PAT-006): the
# SINGLE place this literal is declared -- three call sites
# (``test_interpreter_matrix_env_pinning.py``,
# ``test_migration_robustness.py``, ``test_interpreter_shard_coverage.py``)
# each independently hardcoded it a fourth time before this.
JOB_KEY_PREFIX = "interpreter-matrix-shard-"
# Every derived name on `InterpreterShard` below (exit var, junit filename,
# artifact name, lane label) is computed from `<N>` alone, so this single
# regex (built from `JOB_KEY_PREFIX`) is the one place that shape is parsed.
_JOB_KEY_RE = re.compile(re.escape(JOB_KEY_PREFIX) + r"(\d+)")


@dataclass(frozen=True)
class InterpreterShard:
    """One nightly interpreter-matrix shard's declared identity.

    ``job_key`` must match ``ci-nightly.yml``'s ``jobs:`` key for this shard
    EXACTLY -- this is what lets the coverage-completeness check diff this
    roster against the live workflow file by simple set comparison.

    The properties below (``shard_number``, ``exit_var``, ``junit_filename``,
    ``artifact_name``, ``lane_label``) are the roster-level derivations of
    every per-shard naming convention the workflow and its guard tests rely
    on. Before this, each convention was independently re-derived by a
    different test module with its own regex/``.replace``/``rsplit`` --
    a copy-paste hazard where one deriver could silently drift from another
    (landing pass #5244, LAND-PAT-002). Consumers must use these properties
    instead of re-deriving a shard's names from ``job_key`` themselves.
    """

    job_key: str
    paths: tuple[str, ...]
    ignores: tuple[str, ...] = field(default_factory=tuple)
    suite_key: str = ""

    def resolved_suite_key(self) -> str:
        """The ``--suite-key`` literal this shard's escalation step must use.

        Defaults to ``job_key`` when ``suite_key`` is left empty, so a shard
        added to the roster without an explicit override still gets a
        distinct, non-colliding key (FR-011/FR-015) derived from its own
        job identity rather than silently falling back to a shared default.
        """
        return self.suite_key or self.job_key

    @property
    def shard_number(self) -> int:
        """The shard's numeric ordinal, parsed from ``job_key`` (the single
        SSOT parse -- every other derived name below is computed FROM this,
        never independently re-parsed from ``job_key`` a second way)."""
        match = _JOB_KEY_RE.fullmatch(self.job_key)
        if not match:
            raise ValueError(f"job_key {self.job_key!r} does not match the interpreter-matrix-shard-<N> shape ({_JOB_KEY_RE.pattern!r})")
        return int(match.group(1))

    @property
    def exit_var(self) -> str:
        """The ``$GITHUB_ENV`` exit-code variable this shard's suite,
        escalation, and fail-loud steps must all read/write in common."""
        return f"INTERPRETER_SHARD_{self.shard_number}_EXIT"

    @property
    def junit_filename(self) -> str:
        """The ``--junitxml`` filename (under ``out/reports/``) this shard's
        suite step must write."""
        return f"xunit-nightly-interpreter-3.13-shard-{self.shard_number}.xml"

    @property
    def artifact_name(self) -> str:
        """The ``actions/upload-artifact`` ``name:`` this shard's reports
        upload under."""
        return f"ci-nightly-interpreter-3.13-shard-{self.shard_number}-reports"

    @property
    def lane_label(self) -> str:
        """The short ``interpreter-<N>`` label used to key this shard's
        entry in exit-honesty's per-lane lookup tables (distinct from
        ``resolved_suite_key()``, which is the longer
        ``interpreter-3.13-shard-<N>`` literal passed to the escalation
        script)."""
        return f"interpreter-{self.shard_number}"


# 6 shards total: shards 1-2 unchanged from the initial guess (real,
# measured-good); shards 3-6 are the redrawn split of the initial
# placeholder shard 3, which run 1 proved badly imbalanced (cancelled at the
# 45-minute cap). See the module docstring for the full derivation.
INTERPRETER_SHARDS: tuple[InterpreterShard, ...] = (
    InterpreterShard(
        job_key="interpreter-matrix-shard-1",
        paths=("tests/unit", "tests/status", "tests/cli"),
        suite_key="interpreter-3.13-shard-1",
    ),
    InterpreterShard(
        job_key="interpreter-matrix-shard-2",
        paths=("tests/specify_cli/runtime", "tests/charter", "tests/kernel"),
        suite_key="interpreter-3.13-shard-2",
    ),
    InterpreterShard(
        job_key="interpreter-matrix-shard-3",
        paths=(
            "tests/adversarial",
            "tests/architectural",
            "tests/ast_analysis",
            "tests/consolidation",
            "tests/core",
            "tests/doctrine_synthesizer",
            "tests/integration",
            "tests/invocation",
            "tests/migrate",
            "tests/migration",
            "tests/mission_metadata",
            "tests/orchestrator_api",
            "tests/post_merge",
            "tests/release",
            "tests/reporting",
            "tests/reviews",
            "tests/specify_cli/charter",
            "tests/specify_cli/charter_freshness",
            "tests/specify_cli/charter_runtime",
            "tests/specify_cli/cli",
            "tests/specify_cli/config",
            "tests/specify_cli/decisions",
            "tests/specify_cli/dossier",
            "tests/specify_cli/missions",
            "tests/specify_cli/orchestrator_api",
            "tests/specify_cli/ownership",
            "tests/specify_cli/shims",
            "tests/specify_cli/skills",
            "tests/specify_cli/tasks",
            "tests/specify_cli/tasks_authoring",
            "tests/specify_cli/test_active_mission_removal.py",
            "tests/specify_cli/test_agent_tasks_ports_write_dir.py",
            "tests/specify_cli/test_bytecode_heal.py",
            "tests/specify_cli/test_change_mode_read_boundaries.py",
            "tests/specify_cli/test_doctrine_service_factory.py",
            "tests/specify_cli/test_meta_read_permission_denied_regression.py",
            "tests/specify_cli/test_mission_brief_missing_vs_corrupt.py",
            "tests/specify_cli/test_mission_brief_resilient_write.py",
            "tests/specify_cli/test_mission_metadata_change_mode.py",
            "tests/specify_cli/test_no_manual_ffmerge.py",
            "tests/specify_cli/test_repair_lane_mismatch.py",
            "tests/specify_cli/test_requirement_mapping_coord_surface.py",
            "tests/specify_cli/test_wp_frontmatter_fold.py",
            "tests/specify_cli/upgrade",
            "tests/test_test_venv_bootstrap.py",
        ),
        suite_key="interpreter-3.13-shard-3",
    ),
    InterpreterShard(
        job_key="interpreter-matrix-shard-4",
        paths=(
            "tests/_support",
            "tests/auth",
            "tests/characterization",
            "tests/contract",
            "tests/doctrine",
            "tests/dossier",
            "tests/git",
            "tests/git_ops",
            "tests/mission",
            "tests/missions",
            "tests/scripts",
            "tests/specify_cli/agent_utils",
            "tests/specify_cli/asset_preservation",
            "tests/specify_cli/bulk_edit",
            "tests/specify_cli/charter_lint",
            "tests/specify_cli/charter_preflight",
            "tests/specify_cli/consolidation",
            "tests/specify_cli/contracts",
            "tests/specify_cli/coordination",
            "tests/specify_cli/core",
            "tests/specify_cli/events",
            "tests/specify_cli/git",
            "tests/specify_cli/integration",
            "tests/specify_cli/invocation",
            "tests/specify_cli/mission_v1",
            "tests/specify_cli/readiness",
            "tests/specify_cli/retrospective",
            "tests/specify_cli/test_1716_closeout_regression.py",
            "tests/specify_cli/test_analysis_report_symlink_loops.py",
            "tests/specify_cli/test_atomic_write.py",
            "tests/specify_cli/test_audit_tail_readers.py",
            "tests/specify_cli/test_charter_lifecycle_gates.py",
            "tests/specify_cli/test_doctor_doctrine.py",
            "tests/specify_cli/test_logging_bootstrap.py",
            "tests/specify_cli/test_mid8_contract_sensitive_routing.py",
            "tests/specify_cli/test_mission_brief_overwrite_chokepoint.py",
            "tests/specify_cli/test_mission_discard_marker.py",
            "tests/specify_cli/test_research_drg_nodes.py",
            "tests/specify_cli/test_state_gitignore_migration.py",
            "tests/specify_cli/test_validate_mission_paths_single_caller.py",
            "tests/specify_cli/test_worktrees_index.py",
            "tests/specify_cli/test_wp18_meta_reader_contracts.py",
            "tests/specify_cli/widen",
            "tests/task_utils",
            "tests/test_template",
            "tests/test_worker_home_isolation.py",
            "tests/tracker",
        ),
        suite_key="interpreter-3.13-shard-4",
    ),
    InterpreterShard(
        job_key="interpreter-matrix-shard-5",
        paths=(
            "tests/acceptance",
            "tests/audit",
            "tests/compat",
            "tests/context",
            "tests/docs",
            "tests/evidence",
            "tests/glossary",
            "tests/lanes",
            "tests/policy",
            "tests/research",
            "tests/retrospective",
            "tests/review",
            "tests/runtime",
            "tests/specify_cli/acceptance",
            "tests/specify_cli/charter_packs",
            "tests/specify_cli/compat",
            "tests/specify_cli/docs",
            "tests/specify_cli/live_work",
            "tests/specify_cli/migration",
            "tests/specify_cli/mission_step_contracts",
            "tests/specify_cli/retrospect",
            "tests/specify_cli/review",
            "tests/specify_cli/saas_client",
            "tests/specify_cli/test_bare_prose_false_negative_sample.py",
            "tests/specify_cli/test_brief_pair_atomicity.py",
            "tests/specify_cli/test_charter_pack_registry.py",
            "tests/specify_cli/test_command_template_cleanliness.py",
            "tests/specify_cli/test_delete_scalar.py",
            "tests/specify_cli/test_documentation_template_resolution.py",
            "tests/specify_cli/test_entrypoint_json_mode.py",
            "tests/specify_cli/test_feature_metadata.py",
            "tests/specify_cli/test_feature_metadata_origin.py",
            "tests/specify_cli/test_gitignore_contract.py",
            "tests/specify_cli/test_mid8_direct_routing.py",
            "tests/specify_cli/test_mission_metadata.py",
            "tests/specify_cli/test_mission_type_read_converters.py",
            "tests/specify_cli/test_mission_type_write_boundaries.py",
            "tests/specify_cli/test_read_seam_migration_core.py",
            "tests/specify_cli/test_requirement_id_grammar.py",
            "tests/specify_cli/test_requirement_id_lint.py",
            "tests/specify_cli/test_requirement_mapping.py",
            "tests/specify_cli/test_requirement_reason_parity.py",
            "tests/specify_cli/test_state_contract.py",
            "tests/specify_cli/tool_surface",
            "tests/specify_cli/tracker",
            "tests/tasks",
            "tests/test_frontmatter_dup_key.py",
        ),
        suite_key="interpreter-3.13-shard-5",
    ),
    InterpreterShard(
        job_key="interpreter-matrix-shard-6",
        paths=(
            "tests/agent",
            "tests/ci",
            "tests/coordination",
            "tests/cross_cutting",
            "tests/decisions",
            "tests/init",
            "tests/mission_runtime",
            "tests/next",
            "tests/paths",
            "tests/prompts",
            "tests/readiness",
            "tests/regressions",
            "tests/specify_cli/audit",
            "tests/specify_cli/bootstrap",
            "tests/specify_cli/context",
            "tests/specify_cli/distribution",
            "tests/specify_cli/drg_writers",
            "tests/specify_cli/identity",
            "tests/specify_cli/lanes",
            "tests/specify_cli/next",
            "tests/specify_cli/regression",
            "tests/specify_cli/session_presence",
            "tests/specify_cli/status",
            "tests/specify_cli/test_acceptable_ending.py",
            "tests/specify_cli/test_acceptance_needs_clarification.py",
            "tests/specify_cli/test_canonical_acceptance.py",
            "tests/specify_cli/test_charter_list.py",
            "tests/specify_cli/test_cli",
            "tests/specify_cli/test_codebase_sweep.py",
            "tests/specify_cli/test_configured_command.py",
            "tests/specify_cli/test_documentation_drg_nodes.py",
            "tests/specify_cli/test_intake_sources.py",
            "tests/specify_cli/test_intake_sources_hardening.py",
            "tests/specify_cli/test_lane_regression_guard.py",
            "tests/specify_cli/test_meta_fail_closed_degradation_paths.py",
            "tests/specify_cli/test_no_checklist_surface.py",
            "tests/specify_cli/test_profile_context_migration.py",
            "tests/specify_cli/test_runtime_hard_fail.py",
            "tests/specify_cli/test_state_doctor.py",
            "tests/specify_cli/test_workspace_context_tombstone.py",
            "tests/specify_cli/workspace",
            "tests/state",
            "tests/upgrade",
            "tests/zeitgeist_client",
        ),
        suite_key="interpreter-3.13-shard-6",
    ),
)

INTERPRETER_SHARD_JOB_KEYS: tuple[str, ...] = tuple(shard.job_key for shard in INTERPRETER_SHARDS)


def shard_roster_non_vacuity_violation(
    roster_job_keys: tuple[str, ...],
    real_job_keys: Iterable[str],
) -> str | None:
    """Shared roster-vs-workflow non-vacuity/count-match check (landing pass
    #5244, LAND-PAT-006).

    The roster must be non-empty, and its declared job-key count must equal
    the number of real ``JOB_KEY_PREFIX``-shaped keys ``real_job_keys`` (any
    iterable of job-key strings -- typically a parsed workflow's ``jobs:``
    mapping keys) actually carries. Returns a message describing the
    violation, or ``None`` when they agree.

    Collapses three previously independent copies of this exact check --
    ``test_interpreter_matrix_env_pinning.py``,
    ``test_migration_robustness.py``, and
    ``test_interpreter_shard_coverage.py`` -- each of which separately
    hardcoded the ``interpreter-matrix-shard-`` job-key prefix as a literal
    (a fourth restatement of the naming convention :data:`JOB_KEY_PREFIX`
    now owns) and re-derived the same count comparison. Each of those three
    call sites keeps its own guard test and mutation control; only the
    comparison itself is shared.
    """
    if not roster_job_keys:
        return "INTERPRETER_SHARD_JOB_KEYS must not be empty"
    real_shard_job_keys = {key for key in real_job_keys if key.startswith(JOB_KEY_PREFIX)}
    if len(real_shard_job_keys) != len(roster_job_keys):
        return (
            f"roster declares {len(roster_job_keys)} shard job key(s) {sorted(roster_job_keys)} but "
            f"the workflow defines {len(real_shard_job_keys)} {JOB_KEY_PREFIX}* job(s) {sorted(real_shard_job_keys)}"
        )
    return None
