"""Regression guard for issue #4895 (P0): pre-commit hook clobber.

``policy/hook_installer.py:install()`` performed an unconditional
``os.replace(tmp, hooks_dir / "pre-commit")`` -- no existence check, no
signature check, no backup. ``.git/hooks`` is shared by the main checkout
and every worktree, so a single ``spec-kitty implement WP##`` silently
disabled the operator's own commit-time checks repo-wide, untracked and
unrecoverable (``install_commit_guard`` additionally swallowed every
failure behind a blanket ``except Exception: return None``, so nothing
was ever printed either).

The fix (contract §C-hook, hybrid backup-and-warn + proceed):
  - A pre-existing ``.git/hooks/pre-commit`` that does NOT bear the
    spec-kitty signature (``# Generated by spec-kitty.``) is backed up via
    the WP01 helper ``backup_before_overwrite`` BEFORE the atomic replace.
  - A hook that already bears the signature is replaced with no backup
    churn (green-on-base anchor: this already worked pre-fix).
  - No pre-existing hook is unchanged behaviour (green-on-base anchor).
  - The backup path is returned from ``install_commit_guard`` instead of
    being swallowed by a blanket ``except Exception: return None``, and
    ``lanes.implement_support.create_lane_workspace`` prints it so the
    operator actually sees it in ``implement``'s output.

This module drives the fix through the narrowest public seam that
installs the hook: ``specify_cli.policy.hook_installer.install_commit_guard``
(directly exercised by ``lanes/implement_support.py`` on every
``spec-kitty implement``) for the backup/anchor behaviour, plus a direct,
narrow proof of the ``create_lane_workspace`` wiring (T012) for the
operator-visible surfacing.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.git_repo, pytest.mark.regression]

FOREIGN_HOOK_BODY = "#!/bin/sh\necho 'operator husky hook' >&2\nexit 0\n"
SPEC_KITTY_SIGNATURE = "# Generated by spec-kitty."


def _init_git(repo: Path) -> None:
    repo.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", "--quiet"], cwd=repo, check=True)


def _hooks_dir(repo: Path) -> Path:
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    return hooks_dir


def _write_foreign_hook(repo: Path, body: str = FOREIGN_HOOK_BODY) -> Path:
    hook_path = _hooks_dir(repo) / "pre-commit"
    hook_path.write_text(body, encoding="utf-8")
    hook_path.chmod(0o755)
    return hook_path


def _sidecar_files(hooks_dir: Path) -> list[Path]:
    """Backup sidecars of ``pre-commit``, excluding git's own ``*.sample`` templates.

    ``git init`` ships template files such as ``pre-commit.sample`` in every
    fresh ``.git/hooks`` dir; those are unrelated to the #4895 backup sidecar
    (``pre-commit.<timestamp>``) and must not be mistaken for one.
    """
    return [p for p in hooks_dir.glob("pre-commit.*") if not p.name.endswith(".sample")]


def _hook_path_of(result: object) -> Path:
    """Extract the installed hook path from either return shape.

    Base (pre-fix) ``install_commit_guard`` returns a bare ``Path``; the fix
    returns a ``HookInstallRecord`` whose ``hook_path`` attribute carries it.
    Used only by the two green-on-base anchors below, so they exercise the
    real ``install_commit_guard`` return value on EITHER side of the fix
    without hard-coding the new API shape into an anchor that must also pass
    pre-fix.
    """
    hook_path = getattr(result, "hook_path", None)
    return hook_path if hook_path is not None else result  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# T009 -- foreign hook: backed up, path surfaced, restorable (RED on base)
# ---------------------------------------------------------------------------


def test_foreign_hook_is_backed_up_before_replace(tmp_path: Path) -> None:
    """A foreign pre-existing hook is preserved as a sidecar before install.

    RED on base: base ``install()`` unconditionally ``os.replace``s the
    hook with no existence/signature check and no backup -- the foreign
    body is gone and no sidecar exists.
    """
    from specify_cli.policy.hook_installer import install_commit_guard

    repo = tmp_path / "repo"
    _init_git(repo)
    hook_path = _write_foreign_hook(repo)

    record = install_commit_guard(repo, repo)

    assert record is not None
    assert record.backup_path is not None, "foreign hook must be backed up (#4895)"
    backup_path = record.backup_path

    # Sidecar naming: pre-commit.<timestamp>, sibling of the original.
    assert backup_path.parent == hook_path.parent
    assert backup_path.name.startswith("pre-commit.")
    assert backup_path.name != "pre-commit"

    # Byte-identical to the foreign content that was overwritten.
    assert backup_path.read_bytes() == FOREIGN_HOOK_BODY.encode("utf-8")

    # The installed hook is now the spec-kitty guard, not the foreign body.
    assert SPEC_KITTY_SIGNATURE in hook_path.read_text(encoding="utf-8")

    # Restorable: copying the sidecar back over the live hook recovers the
    # operator's original commit-time checks exactly.
    hook_path.write_bytes(backup_path.read_bytes())
    assert hook_path.read_text(encoding="utf-8") == FOREIGN_HOOK_BODY


# ---------------------------------------------------------------------------
# Anchors (green-on-base): must stay green after the fix too
# ---------------------------------------------------------------------------


def test_signed_hook_is_replaced_with_no_backup(tmp_path: Path) -> None:
    """A hook spec-kitty already installed is replaced with NO backup sidecar.

    Green-on-base: asserted purely through filesystem side effects (no
    sidecar files appear) rather than the new ``.backup_path`` attribute, so
    this anchor holds under BOTH the pre-fix ``Path``-returning API and the
    fixed ``HookInstallRecord``-returning one -- proving the "no backup
    churn for an already-owned hook" behaviour was never broken, not merely
    that the new field happens to read ``None``.
    """
    from specify_cli.policy.hook_installer import install, install_commit_guard

    repo = tmp_path / "repo"
    _init_git(repo)

    # First install writes a genuine spec-kitty-signed hook.
    install(repo)
    hooks_dir = _hooks_dir(repo)
    hook_path = hooks_dir / "pre-commit"
    assert SPEC_KITTY_SIGNATURE in hook_path.read_text(encoding="utf-8")

    result = install_commit_guard(repo, repo)

    assert result is not None
    assert _hook_path_of(result) == hook_path
    assert _sidecar_files(hooks_dir) == [], "a spec-kitty-signed hook must not be backed up"


def test_no_pre_existing_hook_installs_without_backup(tmp_path: Path) -> None:
    """No pre-existing hook: guard is installed, behaviour is unchanged.

    Green-on-base for the same reason as the signed-hook anchor above: only
    filesystem side effects (the installed hook + absence of any sidecar)
    are asserted, not the new ``.backup_path`` attribute.
    """
    from specify_cli.policy.hook_installer import install_commit_guard

    repo = tmp_path / "repo"
    _init_git(repo)
    hooks_dir = repo / ".git" / "hooks"
    # A fresh `git init` may or may not ship sample hooks; ensure none named
    # `pre-commit` are present so this anchor is unambiguous.
    hooks_dir.mkdir(parents=True, exist_ok=True)
    assert not (hooks_dir / "pre-commit").exists()

    result = install_commit_guard(repo, repo)

    assert result is not None
    hook_path = _hook_path_of(result)
    assert hook_path.exists()
    assert SPEC_KITTY_SIGNATURE in hook_path.read_text(encoding="utf-8")
    assert _sidecar_files(hooks_dir) == []


# ---------------------------------------------------------------------------
# Symlinked foreign hook (relies on WP01 symlink-aware backup_before_overwrite)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="os.symlink requires admin/dev mode on Windows",
)
def test_symlinked_foreign_hook_backup_captures_the_link(tmp_path: Path) -> None:
    """A symlinked foreign hook is backed up as a symlink; target untouched."""
    from specify_cli.policy.hook_installer import install_commit_guard

    repo = tmp_path / "repo"
    _init_git(repo)
    hooks_dir = _hooks_dir(repo)

    target = tmp_path / "operator-managed-hook.sh"
    target.write_text(FOREIGN_HOOK_BODY, encoding="utf-8")
    hook_path = hooks_dir / "pre-commit"
    hook_path.symlink_to(target)

    record = install_commit_guard(repo, repo)

    assert record is not None
    backup_path = record.backup_path
    assert backup_path is not None, "symlinked foreign hook must be backed up"

    assert backup_path.is_symlink(), "backup of a symlinked hook must itself be a symlink"
    assert Path(backup_path.readlink()) == target
    # The symlink target file itself was never touched.
    assert target.read_text(encoding="utf-8") == FOREIGN_HOOK_BODY

    # The live hook is now the spec-kitty guard (a regular file, not the
    # old symlink -- os.replace() swaps the directory entry atomically).
    assert not hook_path.is_symlink()
    assert SPEC_KITTY_SIGNATURE in hook_path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# T012 -- implement's output surfaces the backup path (real create_lane_workspace)
# ---------------------------------------------------------------------------


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)


def _init_lane_repo(repo: Path) -> None:
    """Minimal legacy-topology repo good enough for ``allocate_lane_worktree``:
    a ``main`` branch with one commit, no ``coordination_branch`` (no
    ``meta.json``), single lane ``lane-a`` owning ``WP01``.
    """
    repo.mkdir(parents=True, exist_ok=True)
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "t@example.com")
    _git(repo, "config", "user.name", "Test")
    _git(repo, "config", "commit.gpgsign", "false")
    (repo / "README.md").write_text("seed\n")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "seed")


def test_create_lane_workspace_prints_backup_path_when_foreign_hook_preserved(
    tmp_path: Path,
) -> None:
    """``create_lane_workspace`` prints the backup sidecar path (#4895 T012).

    Drives the REAL ``create_lane_workspace`` -- the exact function this
    WP's ``owned_files`` surface (``lanes/implement_support.py``) modifies
    -- through a minimal legacy-topology lane allocation, with a foreign
    ``.git/hooks/pre-commit`` pre-installed. Proves the whole chain: the
    hook is preserved (via ``install_commit_guard``) AND the operator sees
    the sidecar path in the console output the function itself produces,
    not a re-implementation of its wiring.
    """
    from kernel.clock import now_utc_iso
    from specify_cli.lanes.implement_support import create_lane_workspace
    from specify_cli.lanes.models import ExecutionLane, LanesManifest
    from specify_cli.ownership.models import WorkProductKind
    from specify_cli.workspace.context import ResolvedWorkspace

    repo = tmp_path / "repo"
    _init_lane_repo(repo)

    mission_slug = "hook-preservation-demo"
    wp_id = "WP01"

    feature_dir = repo / "kitty-specs" / mission_slug
    tasks_dir = feature_dir / "tasks"
    tasks_dir.mkdir(parents=True)
    wp_file = tasks_dir / f"{wp_id}-demo.md"
    wp_file.write_text(f"---\nwork_package_id: {wp_id}\ndependencies: []\n---\n# {wp_id}\n")

    lanes_manifest = LanesManifest(
        version=1,
        mission_slug=mission_slug,
        mission_id="01ARZ3NDEKTSV4RRFFQ69G5FAV",
        mission_branch="main",
        target_branch="main",
        lanes=[
            ExecutionLane(
                lane_id="lane-a",
                wp_ids=(wp_id,),
                write_scope=(),
                predicted_surfaces=(),
                depends_on_lanes=(),
                parallel_group=0,
            )
        ],
        computed_at=now_utc_iso(),
        computed_from="test",
    )

    resolved_workspace = ResolvedWorkspace(
        mission_slug=mission_slug,
        wp_id=wp_id,
        execution_mode=WorkProductKind.CODE_CHANGE,
        mode_source="explicit",
        resolution_kind="lane_worktree",
        workspace_name=f"{mission_slug}-lane-a",
        worktree_path=repo,  # unused on the CODE_CHANGE path (allocator derives it)
        branch_name=None,
        lane_id="lane-a",
        lane_wp_ids=[wp_id],
        context=None,
    )

    # Plant the operator's foreign hook BEFORE the guard install runs.
    hook_path = _write_foreign_hook(repo)

    from specify_cli.cli import console as console_module

    with patch.object(console_module.console, "print") as mock_print:
        create_lane_workspace(
            repo_root=repo,
            mission_slug=mission_slug,
            wp_id=wp_id,
            wp_file=wp_file,
            resolved_workspace=resolved_workspace,
            lanes_manifest=lanes_manifest,
            declared_deps=[],
            vcs_backend_value="git",
        )

    # The guard replaced the foreign hook with the spec-kitty guard...
    assert SPEC_KITTY_SIGNATURE in hook_path.read_text(encoding="utf-8")

    # ...but preserved a byte-identical sidecar first.
    sidecars = _sidecar_files(hook_path.parent)
    assert len(sidecars) == 1, f"expected exactly one backup sidecar, found {sidecars}"
    assert sidecars[0].read_bytes() == FOREIGN_HOOK_BODY.encode("utf-8")

    # And the operator was actually told about it (the #4895 harm: nothing
    # was ever printed).
    printed_lines = [str(call.args[0]) for call in mock_print.call_args_list if call.args]
    assert any(sidecars[0].name in line for line in printed_lines), f"backup sidecar {sidecars[0]} was not surfaced in implement's output: {printed_lines}"
